#!/usr/bin/env python3
# Build cities/pittsburgh.html from the Cleveland engine with the expanded Pittsburgh data.
import re, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # repo root (this file lives in tools/)
SRC = os.path.join(ROOT, "cleveland.html")
OUT = os.path.join(ROOT, "cities", "pittsburgh.html")
h = open(SRC, encoding="utf-8").read()

DATA = r'''const S = {
  AO:{k:"ATLAS OBSCURA",t:"70 Cool and Unusual Things to Do in Pittsburgh",u:"https://www.atlasobscura.com/things-to-do/pittsburgh-pennsylvania",l:"Atlas Obscura"},
  TA:{k:"TRIPADVISOR",t:"THE 15 BEST Things to Do in Pittsburgh",u:"https://www.tripadvisor.com/Attractions-g53449-Activities-Pittsburgh_Pennsylvania.html",l:"Tripadvisor"},
  USN:{k:"U.S. NEWS",t:"U.S. News Travel — 15 Best Things to Do in Pittsburgh",u:"https://travel.usnews.com/Pittsburgh_PA/Things_To_Do/",l:"U.S. News Travel"},
  PW:{k:"PLANETWARE",t:"Top-Rated Tourist Attractions in Pittsburgh",u:"https://www.planetware.com/tourist-attractions-/pittsburgh-us-pa-pt.htm",l:"PlanetWare"},
  LP:{k:"LONELY PLANET",t:"11 of the best things to do in Pittsburgh",u:"https://www.lonelyplanet.com/articles/top-things-to-do-in-pittsburgh",l:"Lonely Planet"},
  FOD:{k:"FODOR'S",t:"Fodor's Pittsburgh Travel Guide",u:"https://www.fodors.com/world/north-america/usa/pennsylvania/pittsburgh",l:"Fodor's"},
  FRO:{k:"FROMMER'S",t:"Frommer's — Things to See in Pittsburgh",u:"https://www.frommers.com/destinations/pittsburgh/attractions",l:"Frommer's"},
  NATGEO:{k:"NAT GEO",t:"National Geographic — A guide to Pittsburgh",u:"https://www.nationalgeographic.com/travel/article/guide-pittsburgh-americas-characterful-cultural-powerhouse",l:"National Geographic"},
  BRIT:{k:"BRITANNICA",t:"Encyclopaedia Britannica — Pittsburgh, Cultural life",u:"https://www.britannica.com/place/Pittsburgh",l:"Britannica"},
  WIKI:{k:"WIKIPEDIA",t:"List of museums in Pittsburgh",u:"https://en.wikipedia.org/wiki/List_of_museums_in_Pittsburgh",l:"Wikipedia"},
  DTB:{k:"DISCOVER BURGH",t:"Discover the Burgh — A Local's Guide to the Best Things to Do",u:"https://www.discovertheburgh.com/things-to-do-in-pittsburgh/",l:"Discover the Burgh"},
  CT:{k:"CULTURE TRIP",t:"The Best Things To Do In Pittsburgh",u:"https://theculturetrip.com/north-america/usa/pittsburgh",l:"Culture Trip"},
  UPA:{k:"UNCOVERING PA",t:"Uncovering PA — Pittsburgh guides",u:"https://uncoveringpa.com",l:"Uncovering PA"},
  NP:{k:"NEXTPITTSBURGH",t:"NextPittsburgh — neighborhoods & things to do",u:"https://nextpittsburgh.com",l:"NextPittsburgh"},
  PGHMAG:{k:"PITTSBURGH MAG",t:"Pittsburgh Magazine — Best of the 'Burgh",u:"https://www.pittsburghmagazine.com/best-of-pittsburgh/",l:"Pittsburgh Magazine"},
  VP:{k:"VISIT PITTSBURGH",t:"Visit Pittsburgh — the official CVB",u:"https://www.visitpittsburgh.com/things-to-do/",l:"Visit Pittsburgh"},
  CMP:{k:"CARNEGIE MUSEUMS",t:"Carnegie Museums of Pittsburgh (official)",u:"https://carnegiemuseums.org/",l:"carnegiemuseums.org"},
  CMOA:{k:"CMOA (OFFICIAL)",t:"Carnegie Museum of Art — official site",u:"https://cmoa.org/",l:"cmoa.org"},
  CMNH:{k:"CMNH (OFFICIAL)",t:"Carnegie Museum of Natural History — official site",u:"https://carnegiemnh.org/",l:"carnegiemnh.org"},
  ZOO:{k:"ZOO (OFFICIAL)",t:"Pittsburgh Zoo & Aquarium — official site",u:"https://www.pittsburghzoo.org/",l:"pittsburghzoo.org"},
  AVI:{k:"AVIARY (OFFICIAL)",t:"National Aviary — official site",u:"https://www.aviary.org/",l:"aviary.org"},
  PITT:{k:"UNIV OF PITTSBURGH",t:"University of Pittsburgh — Guide to Oakland & Pittsburgh",u:"https://www.provost.pitt.edu/acc-aln-conference/guide",l:"pitt.edu"},
  CMU:{k:"CARNEGIE MELLON",t:"Carnegie Mellon — Discover Pittsburgh",u:"https://www.cmu.edu/admission/campus-experience/discover-pittsburgh",l:"cmu.edu"},
  DUQ:{k:"DUQUESNE UNIV",t:"Duquesne University — Our Pittsburgh Community",u:"https://www.duq.edu/life-at-duquesne/our-campus/our-pittsburgh-community.php",l:"duq.edu"},
  CHAT:{k:"CHATHAM UNIV",t:"Chatham University — Free Activities in Pittsburgh",u:"https://www.pulse.chatham.edu",l:"chatham.edu"},
  ROS:{k:"RIVERS OF STEEL",t:"Rivers of Steel — Carrie Furnaces & Mon Valley heritage",u:"https://riversofsteel.com/",l:"Rivers of Steel"},
  BOH:{k:"BATTLE OF HOMESTEAD",t:"Battle of Homestead Foundation — the Pump House",u:"https://battleofhomestead.org/",l:"Battle of Homestead Fdn"},
  ACP:{k:"ALLEGHENY PARKS",t:"Allegheny County Parks",u:"https://www.alleghenycounty.us/Parks-and-Events/Parks/",l:"Allegheny County Parks"},
  AUD:{k:"AUDUBON W. PA",t:"Audubon Society of Western PA — Beechwood Farms",u:"https://www.aswp.org/",l:"Audubon Society of W PA"},
  TRIB:{k:"TRIBLIVE",t:"TribLive (Pittsburgh Tribune-Review)",u:"https://triblive.com/",l:"TribLive"},
  VWC:{k:"VISIT WASH. CO",t:"Visit Washington County PA",u:"https://www.visitwashingtoncountypa.com/",l:"Visit Washington County"},
  OBSREP:{k:"OBSERVER-REPORTER",t:"Observer-Reporter (Washington, PA)",u:"https://www.observer-reporter.com/",l:"Observer-Reporter"},
  ALM:{k:"THE ALMANAC",t:"The Almanac (South Hills)",u:"https://www.thealmanac.net/",l:"The Almanac"},
  PABL:{k:"PA BUCKET LIST",t:"PA Bucket List — Washington County attractions",u:"https://pabucketlist.com/",l:"PA Bucket List"},
  PHLF:{k:"PGH LANDMARKS",t:"Pittsburgh History & Landmarks Foundation",u:"https://phlf.org/",l:"PHLF"},
  ADD:{k:"ADDED",t:"Well-known landmarks the oddity lists skip because they are not hidden",u:"",l:"My addition — verify hours before visiting"}
};

const AREAS = [
  {id:"DT",  n:"Downtown, North Shore & North Side", c:"var(--c-dt)"},
  {id:"OAK", n:"Oakland & the East End",             c:"var(--c-uc)"},
  {id:"SS",  n:"South Side, Mount Washington & the West End", c:"var(--c-ws)"},
  {id:"SH",  n:"South Hills & the Southwest",         c:"var(--c-sh)"},
  {id:"EV",  n:"Eastern Suburbs & River Valleys",     c:"var(--c-ev)"},
  {id:"DY",  n:"Day Trips & the Laurel Highlands",    c:"var(--c-sub)"}
];

const P = [
/* == DOWNTOWN, NORTH SHORE & NORTH SIDE == */
{t:1,a:"DT",n:"Point State Park & the Fort Pitt Museum",ad:"601 Commonwealth Pl",la:40.4417,ln:-80.0092,
 w:"The tip of the Golden Triangle where the Allegheny and Monongahela meet to form the Ohio, marked by a giant fountain, with the Fort Pitt Museum telling the French-and-Indian-War story on the very spot.",
 k:"Park free and always open; fountain runs in season. Museum (Heinz History Center-run) daily 10–5.",s:[["VP",""],["LP",""],["FRO",""],["CHAT",""]]},
{t:2,a:"DT",n:"Fort Pitt Block House",ad:"Point State Park, Downtown",la:40.4412,ln:-80.0098,
 w:"A 1764 brick redoubt of Fort Pitt — the oldest structure in Western Pennsylvania and the only surviving piece of the fort — tucked inside Point State Park.",
 k:"Free and open to the public since 1895; run by the Fort Pitt Society, DAR. Approximate pin.",s:[["WIKI",""],["TA",""]]},
{t:2,a:"DT",n:"Great Allegheny Passage — Pittsburgh trailhead",ad:"Point State Park (waters-edge medallion)",la:40.4416,ln:-80.0100,
 w:"The northern terminus of the 150-mile GAP rail-trail to Cumberland, MD, where it links the C&O Canal towpath all the way to Washington, DC — the mile-zero medallion sits at the very Point.",
 k:"Free, always open; bike and kayak rentals nearby. The ride is the draw. Approximate pin.",s:[["VP",""],["USN",""]]},
{t:3,a:"DT",n:"Three Rivers Heritage Trail",ad:"Both banks of the three rivers",la:40.4460,ln:-80.0075,
 w:"A ~35-mile riverfront multi-use trail lacing Downtown to the neighbourhoods on both banks, used by more than half a million people a year and a National Recreation Trail since 2010.",
 k:"Free, always open. Best stretches: the North Shore and the Eliza Furnace 'Jail Trail'. Approximate pin.",s:[["USN",""],["WIKI",""]]},
{t:1,a:"DT",n:"The Andy Warhol Museum",ad:"117 Sandusky St, North Shore",la:40.4485,ln:-80.0025,
 w:"Seven floors devoted to Pittsburgh-born Andy Warhol — the largest single-artist museum in North America, from the soup cans to the floating Silver Clouds room.",
 k:"Admission charged; some seasons half-price Friday evenings. Closed Tuesdays.",s:[["CMP",""],["TA",""],["CMU",""],["VP",""]]},
{t:1,a:"DT",n:"Mattress Factory",ad:"500 Sampsonia Way, North Side",la:40.4585,ln:-80.0132,
 w:"A museum of room-sized, permanent installation art you walk through — Yayoi Kusama's mirrored infinity room among them — in a former mattress warehouse on the North Side.",
 k:"Admission charged; closed Mon–Tue. Pair with a Mexican War Streets walk.",s:[["AO",""],["TA",""],["VP",""]]},
{t:1,a:"DT",n:"Senator John Heinz History Center",ad:"1212 Smallman St, Strip District",la:40.4468,ln:-79.9910,
 w:"Pennsylvania's largest history museum and a Smithsonian affiliate — six floors on Pittsburgh's steel, glass and sports story, the Heinz 57 kitchen, a real Mister Rogers set, and the Western PA Sports Museum.",
 k:"Admission charged. Allow 2–3 hours. In the Strip; combine with a food crawl.",s:[["VP",""],["PITT",""],["TA",""]]},
{t:2,a:"DT",n:"National Aviary",ad:"700 Arch St, North Side",la:40.4534,ln:-80.0093,
 w:"The country's only congressionally-designated National Aviary — walk-through free-flight rooms with 500+ birds from penguins to a two-toed sloth — called 'hugely underrated' by National Geographic.",
 k:"Admission charged. Great with kids. Closed some holidays.",s:[["AVI",""],["NATGEO",""],["PW",""],["USN",""]]},
{t:2,a:"DT",n:"Kamin Science Center (formerly Carnegie Science Center)",ad:"1 Allegheny Ave, North Shore",la:40.4457,ln:-80.0177,
 w:"Four floors of hands-on science on the North Shore, plus a planetarium, the WWII submarine USS Requin moored outside, and the beloved Miniature Railroad & Village.",
 k:"Admission charged; the sub is a separate ticket. Busy on weekends.",s:[["CMP",""],["VP",""],["TA",""]]},
{t:2,a:"DT",n:"Children's Museum of Pittsburgh",ad:"10 Children's Way, North Side",la:40.4530,ln:-80.0090,
 w:"A nationally-ranked hands-on museum for younger kids — a giant Waterplay hall, a Nursery, MAKESHOP tinkering, and Mister Rogers artefacts — beside the old Buhl planetarium.",
 k:"Admission charged; best for under-10s. Pair with the Warhol next door.",s:[["VP",""],["NP",""],["TA",""]]},
{t:2,a:"DT",n:"Randyland",ad:"1501 Arch St, Mexican War Streets",la:40.4577,ln:-80.0110,
 w:"A free, riotously colourful found-art courtyard and house by folk artist Randy Gilson — one of the most joyful corners of the city, and an Atlas Obscura favourite.",
 k:"Free, outdoors, daytime. Approximate pin in the Mexican War Streets.",s:[["AO",""],["CT",""],["NP",""]]},
{t:2,a:"DT",n:"Bicycle Heaven",ad:"1800 Preble Ave, Chateau",la:40.4530,ln:-80.0260,
 w:"The world's largest bicycle museum and shop — some 4,000 bikes floor to ceiling, including the banana-seat Bowden Spacelander and bikes from films. Free, and gloriously overwhelming.",
 k:"Free. Part shop, part museum. Approximate pin near the Ohio River.",s:[["AO",""],["TA",""],["NP",""]]},
{t:2,a:"DT",n:"St. Anthony's Chapel",ad:"1704 Harpster St, Troy Hill",la:40.4614,ln:-79.9880,
 w:"A hilltop Troy Hill chapel holding the largest collection of Catholic relics in North America — some 5,000 of them, plus life-sized Stations of the Cross carved in Bavaria.",
 k:"Free; limited open hours — check ahead. Quietly astonishing. Approximate pin.",s:[["AO",""],["DTB",""]]},
{t:2,a:"DT",n:"August Wilson African American Cultural Center",ad:"980 Liberty Ave, Cultural District",la:40.4432,ln:-80.0010,
 w:"The city's hub for Black arts, culture and history in the Cultural District — galleries, a 500-seat theatre and 200+ performances a year — named for the Pittsburgh-born playwright.",
 k:"Galleries free; performances ticketed. Approximate pin.",s:[["VP",""],["TA",""],["CMU",""]]},
{t:2,a:"DT",n:"Heinz Hall",ad:"600 Penn Ave, Cultural District",la:40.4427,ln:-80.0015,
 w:"A lavish 1927 former movie palace, restored in 1971 as the 2,676-seat home of the Pittsburgh Symphony Orchestra — the anchor of the Cultural District.",
 k:"Lobby and shows by ticket; catch a symphony or a tour. Approximate pin.",s:[["BRIT",""],["VP",""]]},
{t:2,a:"DT",n:"PNC Park",ad:"115 Federal St, North Shore",la:40.4469,ln:-80.0057,
 w:"Widely called the most beautiful ballpark in America — an intimate riverfront park where the Pirates play against the full Downtown skyline framed beyond the outfield.",
 k:"Best on a game night; the riverwalk and Clemente Bridge views are free any time.",s:[["VP",""],["TA",""],["ADD",""]]},
{t:2,a:"DT",n:"Allegheny Observatory",ad:"159 Riverview Ave, Perry North",la:40.4826,ln:-80.0206,
 w:"A historic University of Pittsburgh research observatory in Riverview Park — one of the world's major astronomical observatories — offering free public tours (reservations required) April through October.",
 k:"Free; reserve ahead. ~4 miles north of Downtown. Approximate pin.",s:[["PITT",""],["AO",""]]},
{t:2,a:"DT",n:"Maxo Vanka Murals, St. Nicholas Croatian Catholic Church",ad:"24 Maryland Ave, Millvale",la:40.4820,ln:-79.9770,
 w:"Twenty-five socially-charged 1937 and 1941 murals by Croatian immigrant Maxo Vanka on immigration, industry and social justice, covering the walls of a Millvale church.",
 k:"Docent-led tours by the Society to Preserve the Millvale Murals; reserve. Approximate pin.",s:[["PITT",""],["NP",""]]},
{t:3,a:"DT",n:"Roberto Clemente Bridge & the Three Sisters",ad:"6th/7th/9th St bridges",la:40.4460,ln:-80.0050,
 w:"Three near-identical yellow self-anchored suspension bridges — the only such trio anywhere — the Clemente closed to cars on game days for a pedestrian stream to PNC Park.",
 k:"Free; walk the Clemente Bridge for the classic skyline shot. Approximate pin.",s:[["VP",""],["ADD",""]]},
{t:3,a:"DT",n:"Fred Rogers Memorial statue",ad:"North Shore Riverfront Park",la:40.4462,ln:-80.0110,
 w:"A quiet, much-loved bronze of Pittsburgh's own Mister Rogers tying his shoe, looking across the river to the city where he made the neighbourhood.",
 k:"Free, outdoors, always there. A two-minute stop on a North Shore walk. Approximate pin.",s:[["ADD",""]]},
{t:3,a:"DT",n:"Acrisure Stadium",ad:"100 Art Rooney Ave, North Shore",la:40.4467,ln:-80.0158,
 w:"The 2001 riverfront stadium (formerly Heinz Field) home to the NFL Steelers and Pitt Panthers, with skyline and river views and behind-the-scenes tours.",
 k:"Best on a game day; tours otherwise. Approximate pin.",s:[["USN",""],["FOD",""]]},
{t:3,a:"DT",n:"Market Square & the Cultural District",ad:"Market Square, Downtown",la:40.4410,ln:-80.0020,
 w:"The pedestrian heart of Downtown — cafés and a farmers' market by day — a block from the Cultural District's theatres and public art along Penn and Liberty.",
 k:"Free to wander; liveliest at lunch and on event nights.",s:[["VP",""],["BRIT",""]]},
{t:3,a:"DT",n:"PPG Place Wintergarden",ad:"Third Ave & Market St, Downtown",la:40.4406,ln:-80.0033,
 w:"Philip Johnson's glass 'castle' of a skyscraper, whose glass-roofed Wintergarden atrium and plaza host a seasonal ice rink and a giant winter tree.",
 k:"Plaza free; rink is seasonal and ticketed.",s:[["TA",""],["ADD",""]]},
{t:3,a:"DT",n:"City of Asylum / Alphabet City",ad:"40 W North Ave, North Side",la:40.4560,ln:-80.0100,
 w:"A sanctuary for exiled writers running free literary events and jazz, anchored by the Alphabet City bookstore-and-restaurant and a row of art-covered 'house publications'.",
 k:"Free events; check the calendar. Bookstore has café hours.",s:[["NP",""],["CT",""]]},
{t:3,a:"DT",n:"Photo Antiquities Museum of Photographic History",ad:"531 E Ohio St, Deutschtown",la:40.4535,ln:-79.9995,
 w:"One of few U.S. museums devoted to 19th-century photography — daguerreotypes, hundreds of vintage cameras, Civil War images and rare early photographs of Pittsburgh.",
 k:"Small; largely by appointment — call ahead. Approximate pin.",s:[["DTB",""],["WIKI",""]]},
{t:3,a:"DT",n:"PPG Paints Arena",ad:"1001 Fifth Ave, Uptown",la:40.4395,ln:-79.9895,
 w:"Pittsburgh's 18,000-seat arena, home of the NHL Penguins and the city's biggest concert stage, on the edge of the Hill District.",
 k:"Visit on an event night. Approximate pin.",s:[["TA",""]]},
{t:3,a:"DT",n:"Kayak Pittsburgh",ad:"River Front Plaza, North Shore",la:40.4448,ln:-79.9950,
 w:"Seasonal kayak, canoe and hydrobike rentals launching straight onto the Allegheny for a paddle under the bridges with the skyline overhead.",
 k:"~$45 for two hours incl. life jacket; May–Oct, weather permitting. Approximate pin.",warn:1,s:[["VP",""]]},
{t:3,a:"DT",n:"Fineview Overlook",ad:"308 Catoma St, Fineview",la:40.4640,ln:-80.0060,
 w:"A North Side hilltop overlook — a grand, crowd-free alternative to Mount Washington — reached by the Fineview 'Rising Main' step-streets.",
 k:"Free, outdoors. Steep steps; a local hidden gem. Approximate pin.",s:[["NP",""]]},
/* == OAKLAND & THE EAST END == */
{t:1,a:"OAK",n:"Cathedral of Learning & the Nationality Rooms",ad:"4200 Fifth Ave, Oakland",la:40.4444,ln:-79.9531,
 w:"Pitt's 42-storey Gothic tower — the tallest university building in the Western Hemisphere — whose lower floors hold 31 Nationality Rooms, each a working classroom built in the style of a different culture.",
 k:"Commons Room free; the rooms have tour hours / small fees. Go up for the view.",s:[["PITT",""],["FOD",""],["VP",""]]},
{t:1,a:"OAK",n:"Carnegie Museum of Natural History",ad:"4400 Forbes Ave, Oakland",la:40.4435,ln:-79.9497,
 w:"One of the great American natural-history museums — 'Dippy' the Diplodocus out front, the T. rex holotype and a world-class Dinosaurs in Their Time hall, and 1,300+ gems and minerals below.",
 k:"One ticket covers Natural History and the Museum of Art. Closed some Tuesdays.",s:[["CMNH",""],["PW",""],["TA",""],["BRIT",""]]},
{t:1,a:"OAK",n:"Carnegie Museum of Art",ad:"4400 Forbes Ave, Oakland",la:40.4432,ln:-79.9500,
 w:"Andrew Carnegie's 'museum of modern art' from 1895, host of the Carnegie International, strong on Impressionism and holding the 70,000-image Teenie Harris archive of Black Pittsburgh.",
 k:"Shares a ticket and building with Natural History. Closed some Tuesdays.",s:[["CMOA",""],["USN",""],["PW",""],["VP",""]]},
{t:1,a:"OAK",n:"Phipps Conservatory and Botanical Gardens",ad:"1 Schenley Dr, Oakland",la:40.4390,ln:-79.9478,
 w:"A glittering 1893 glasshouse on the edge of Schenley Park — 23 gardens of orchids, palms and seasonal flower shows, plus a Chihuly-dotted sunken garden.",
 k:"Admission charged. The seasonal shows (spring, fall, winter light) are the draw.",s:[["VP",""],["BRIT",""],["CMU",""],["PW",""]]},
{t:1,a:"OAK",n:"Heinz Memorial Chapel",ad:"4200 Fifth Ave, Oakland",la:40.4462,ln:-79.9527,
 w:"A 1938 French-Gothic chapel on Pitt's campus famous for 23 Charles Connick stained-glass windows — the transept pair, up to 73 feet, are among the tallest in the world.",
 k:"Free; open most weekdays, sometimes closed Saturdays for weddings. Look up.",s:[["PITT",""],["TA",""],["DTB",""]]},
{t:2,a:"OAK",n:"The Frick Pittsburgh",ad:"7227 Reynolds St, Point Breeze",la:40.4470,ln:-79.9010,
 w:"Henry Clay Frick's estate in Point Breeze — the Frick Art Museum, his preserved Gilded-Age mansion 'Clayton', and a car-and-carriage museum — free to walk, on wooded grounds.",
 k:"Grounds and Art Museum free; Clayton tours ticketed. Closed Mondays.",s:[["VP",""],["PGHMAG",""],["TA",""]]},
{t:2,a:"OAK",n:"Pittsburgh Zoo & Aquarium",ad:"7370 Baker St, Highland Park",la:40.4870,ln:-79.9200,
 w:"Pennsylvania's largest zoo and aquarium — 77 acres and roughly 4,000 animals from tigers and gorillas to a PPG Aquarium — climbing the hillside above Highland Park.",
 k:"Admission charged. Lots of walking and hills; good half-day with kids.",s:[["ZOO",""],["USN",""],["PW",""],["VP",""]]},
{t:2,a:"OAK",n:"Schenley Park",ad:"Schenley Dr, Oakland",la:40.4350,ln:-79.9450,
 w:"A 456-acre 1889 Olmsted-era park wrapping Oakland — Panther Hollow's wooded trails and lake, a golf course and ice rink, and the PNC carousel at Schenley Plaza.",
 k:"Free; hosts the Vintage Grand Prix each July. Phipps sits inside it. Approximate pin.",s:[["DTB",""],["TA",""],["VP",""]]},
{t:2,a:"OAK",n:"The Clemente Museum",ad:"3339 Penn Ave, Lawrenceville",la:40.4665,ln:-79.9640,
 w:"The world's largest exhibited collection of Roberto Clemente artefacts, in an 1898 firehouse (Engine House 25) assembled by photographer Duane Rieder.",
 k:"Guided tours only (~75 min), by reservation; no walk-ins. Approximate pin.",warn:1,s:[["UPA",""],["TA",""],["DTB",""]]},
{t:2,a:"OAK",n:"Stephen Foster Memorial",ad:"4301 Forbes Ave, Oakland",la:40.4415,ln:-79.9533,
 w:"A 1937 hall beside the Cathedral of Learning housing a free museum on America's first professional songwriter, plus two university theatres, in a twelve-sided Gothic chamber with Connick glass.",
 k:"Museum free, Mon–Fri 9–4. Approximate pin.",s:[["PITT",""],["WIKI",""]]},
{t:2,a:"OAK",n:"Hunt Institute for Botanical Documentation",ad:"5th floor, Hunt Library, 4909 Frew St, CMU",la:40.4415,ln:-79.9440,
 w:"A Carnegie Mellon research institute on the history of botany that mounts free public exhibitions of botanical art, including its landmark International Exhibition of Botanical Art & Illustration.",
 k:"Free; galleries open Tue–Fri, Monday by appointment. Approximate pin.",s:[["CMU",""],["AO",""]]},
{t:2,a:"OAK",n:"Frick Fine Arts Building & the Nicholas Lochoff Cloister",ad:"650 Schenley Dr, Oakland",la:40.4406,ln:-79.9503,
 w:"Pitt's Italian-Renaissance fine-arts building — a 1965 gift of Helen Clay Frick — with an open cloister of Nicholas Lochoff's full-scale reproductions of Florentine masterpieces and a University Art Gallery.",
 k:"Free; adjacent to Schenley Plaza. Approximate pin.",s:[["PITT",""],["AO",""]]},
{t:2,a:"OAK",n:"Schenley Plaza & the Mary Schenley Memorial Fountain",ad:"4100 Forbes Ave, Oakland",la:40.4416,ln:-79.9522,
 w:"A restored green plaza at the gateway to Schenley Park, centred on Victor Brenner's 1918 bronze fountain 'A Song to Nature' — Brenner also designed the Lincoln cent.",
 k:"Free; a carousel, food kiosks and lawns ring the Carnegie and Pitt. Approximate pin.",s:[["PITT",""],["NP",""]]},
{t:2,a:"OAK",n:"Walking to the Sky",ad:"Warner Hall lawn, Carnegie Mellon",la:40.4437,ln:-79.9430,
 w:"Jonathan Borofsky's 100-foot stainless-steel pole angled at 75 degrees with figures striding skyward — a signature photo spot on the CMU campus by the alumnus sculptor.",
 k:"Free, outdoors, always there. Approximate pin.",s:[["CMU",""]]},
{t:2,a:"OAK",n:"Randy Pausch Memorial Bridge",ad:"Gates Center to Purnell, Carnegie Mellon",la:40.4440,ln:-79.9445,
 w:"A 230-foot pedestrian bridge threaded with 7,000+ programmable LEDs honouring professor Randy Pausch, running student-designed light shows over the ravine between CS and drama.",
 k:"Free; best after dark for the ~15-minute light loop. Approximate pin.",s:[["CMU",""]]},
{t:2,a:"OAK",n:"Pittsburgh Glass Center",ad:"5472 Penn Ave, Friendship",la:40.4642,ln:-79.9329,
 w:"A nonprofit public-access glass-art centre with a contemporary gallery and live hot-shop glassblowing demonstrations on the Penn Avenue arts corridor.",
 k:"Self-guided free; demos and a monthly First-Friday open house. Approximate pin.",s:[["VP",""],["DTB",""]]},
{t:2,a:"OAK",n:"Highland Park & the Entry Garden",ad:"Reservoir Dr, Highland Park",la:40.4880,ln:-79.9210,
 w:"An East End city park built around a walkable reservoir loop, entered through an ornate 1890s Victorian garden of fountains and reflecting pools, next to the zoo.",
 k:"Free; a flat, popular walking loop. Approximate pin.",s:[["DTB",""],["VP",""]]},
{t:3,a:"OAK",n:"Center for PostNatural History",ad:"4913 Penn Ave, Garfield",la:40.4640,ln:-79.9470,
 w:"A tiny, brilliant museum of life altered by humans — transgenic mice, 'atomic' fruit flies, a taxidermied silkworm empire — deadpan and unforgettable.",
 k:"Free / donation; very limited hours (often weekends) — check first. Approximate pin.",s:[["AO",""],["CT",""]]},
{t:3,a:"OAK",n:"Carnegie Library of Pittsburgh (Main)",ad:"4400 Forbes Ave, Oakland",la:40.4429,ln:-79.9503,
 w:"Carnegie's grand 1895 flagship library, free to the public and beautiful inside — the civic heart of his 'free to the people' Oakland cultural complex.",
 k:"Free. Walk in and look up. Adjacent to the Carnegie Museums.",s:[["PITT",""],["CHAT",""]]},
{t:3,a:"OAK",n:"Soldiers & Sailors Memorial Hall & Museum",ad:"4141 Fifth Ave, Oakland",la:40.4436,ln:-79.9560,
 w:"A monumental 1910 Beaux-Arts hall — one of the country's largest memorials to all who served — with a military museum spanning the Civil War to recent conflicts.",
 k:"Modest admission (free/discounted with student ID); Mon–Sat 10–4.",s:[["PITT",""],["ADD",""]]},
{t:3,a:"OAK",n:"Allegheny Cemetery",ad:"4734 Butler St, Lawrenceville",la:40.4720,ln:-79.9560,
 w:"One of America's oldest garden cemeteries (1844) — rolling, wooded and full of Pittsburgh history, from Stephen Foster to steel barons — with a self-guided tour map.",
 k:"Free, open daylight hours. Grab a notable-graves map at the gate. Approximate pin.",s:[["AO",""],["NP",""]]},
{t:3,a:"OAK",n:"Frick Park & the Frick Environmental Center",ad:"2005 Beechwood Blvd",la:40.4340,ln:-79.9040,
 w:"Pittsburgh's largest city park — 600+ wooded acres of ravines and trails in the East End, with a net-zero green environmental center at the Beechwood gate.",
 k:"Free, always open. Real trails; wear shoes. Approximate pin.",s:[["DTB",""],["ADD",""]]},
{t:3,a:"OAK",n:"Mellon Park Walled Garden",ad:"6300 Fifth Ave, Point Breeze",la:40.4520,ln:-79.9130,
 w:"A half-acre 1920s Renaissance-style walled garden — the last remnant of the demolished Mellon estate — with a Shakespeare herb-garden section and summer performances.",
 k:"Free; a popular photo and wedding spot. Approximate pin.",s:[["VP",""],["TA",""]]},
{t:3,a:"OAK",n:"The Fence",ad:"The Cut, Carnegie Mellon",la:40.4433,ln:-79.9425,
 w:"A CMU landmark once ranked the most-painted object in the world — students repaint it nightly (midnight–6am, brushes only) as a rolling campus message board.",
 k:"Free, outdoors. The original collapsed under its own paint in 1993. Approximate pin.",s:[["CMU",""]]},
{t:3,a:"OAK",n:"Kraus Campo",ad:"Posner Center rooftop, Carnegie Mellon",la:40.4432,ln:-79.9418,
 w:"A 2005 rooftop garden and public artwork by Mel Bochner with landscape architect Michael Van Valkenburgh — orange paths, plantings and a numeric-pattern platform, little-known and contemplative.",
 k:"Free; atop the Posner Center. Approximate pin.",s:[["CMU",""]]},
/* == SOUTH SIDE, MOUNT WASHINGTON & THE WEST END == */
{t:1,a:"SS",n:"Duquesne Incline",ad:"1197 W Carson St, Mount Washington",la:40.4390,ln:-80.0175,
 w:"An 1877 wooden funicular that hauls you up Mount Washington in original cable cars to an observation deck with the classic postcard view of the three rivers and the Point.",
 k:"Small fare each way. Ride up for the overlook; go at dusk.",s:[["VP",""],["DUQ",""],["TA",""]]},
{t:1,a:"SS",n:"Grandview Avenue Overlook, Mount Washington",ad:"Grandview Ave, Mount Washington",la:40.4300,ln:-80.0100,
 w:"The clifftop promenade named one of America's best views — the whole Golden Triangle laid out below, with overlook platforms strung between the two inclines.",
 k:"Free, always open. Best at sunset and after dark. Approximate pin.",s:[["VP",""],["USN",""]]},
{t:2,a:"SS",n:"Monongahela Incline",ad:"8 Grandview Ave (lower: W Carson St)",la:40.4310,ln:-80.0050,
 w:"The oldest continuously operating funicular in the United States (1870), still a working commuter line up Mount Washington from Station Square.",
 k:"Small fare; part of the transit system. Pair with the Grandview overlook.",s:[["AO",""],["VP",""]]},
{t:2,a:"SS",n:"West End Overlook Park",ad:"Marlow St, West End",la:40.4470,ln:-80.0350,
 w:"A four-acre bluff-top park with a head-on skyline view straight up the point where the rivers meet — beloved by photographers and far quieter than Mount Washington.",
 k:"Free; small parking lot on site. Approximate pin.",s:[["AO",""],["DTB",""],["UPA",""]]},
{t:2,a:"SS",n:"Gateway Clipper Fleet",ad:"350 W Station Square Dr, South Shore",la:40.4340,ln:-80.0130,
 w:"America's premier riverboat sightseeing fleet, cruising the three rivers since 1958 with narrated skyline, dining and holiday cruises — plus game-day shuttles.",
 k:"Ticketed; multiple departures daily, fewer in winter. Approximate pin.",s:[["TA",""],["VP",""]]},
{t:3,a:"SS",n:"South Side Slopes city steps",ad:"South Side Slopes",la:40.4270,ln:-79.9820,
 w:"Pittsburgh has more public staircases than any US city, and the South Side Slopes are the densest — hundreds of steps threading between hillside houses, with the annual StepTrek walk.",
 k:"Free, outdoors, steep. Wear real shoes; grab a Slopes steps map. Approximate pin.",s:[["NP",""],["AO",""]]},
{t:3,a:"SS",n:"East Carson Street, South Side",ad:"E Carson St, South Side Flats",la:40.4285,ln:-79.9750,
 w:"One of the country's longest intact Victorian commercial streets — a mile-plus of 19th-century storefronts that turns into Pittsburgh's rowdiest bar strip after dark.",
 k:"Free to stroll; daytime for the architecture, night for the bars. Approximate pin.",s:[["DTB",""],["ADD",""]]},
{t:3,a:"SS",n:"Station Square",ad:"125 W Station Square Dr",la:40.4340,ln:-80.0140,
 w:"A riverfront complex in a former railroad terminal — the Bessemer Court of salvaged steel-mill relics, the Gateway Clipper cruises and a fountain show.",
 k:"Free to walk; cruises and dining ticketed. Lower station of the Mon Incline.",s:[["VP",""],["ADD",""]]},
{t:3,a:"SS",n:"Point of View statue",ad:"Grandview Ave at Sweetbriar St, Mount Washington",la:40.4295,ln:-80.0130,
 w:"A 2006 bronze by James A. West of the 1770 face-to-face meeting of George Washington and Seneca leader Guyasuta, perched on the edge of Mount Washington with the skyline behind.",
 k:"Free, outdoors, always accessible. Approximate pin.",s:[["AO",""],["VP",""]]},
{t:3,a:"SS",n:"Emerald View Park",ad:"Grandview Ave area, Mount Washington",la:40.4290,ln:-80.0180,
 w:"A 257-acre park wrapping Mount Washington with ~10 miles of wooded single-track trails and skyline overlooks — a hiking alternative to the crowded promenade.",
 k:"Free; the Grandview loop is ~4.9 mi, moderate. Approximate pin.",s:[["VP",""],["TA",""]]},
{t:3,a:"SS",n:"Beechview–Seldom Seen Greenway",ad:"Saw Mill Run Blvd trailhead, Beechview",la:40.4090,ln:-80.0250,
 w:"A hidden ~100-acre urban nature preserve on a former farming hamlet, with the 120-year-old Seldom Seen Arch and graffiti-covered railroad tracks.",
 k:"Free; short easy trail (~0.6 mi). The trailhead pull-off is easy to miss. Approximate pin.",s:[["AO",""],["CT",""],["UPA",""]]},
/* == SOUTH HILLS & THE SOUTHWEST == */
{t:1,a:"SH",n:"Pennsylvania Trolley Museum",ad:"1 Electric Way, Washington, PA",la:40.1935,ln:-80.2480,
 w:"A museum of restored streetcars where admission includes a four-mile scenic ride on a vintage trolley, plus exhibits, a theatre and a store — the South Hills' signature day out.",
 k:"Ticketed (adults ~$20); hours vary by season, last full ride ~3pm. ~40 min south. Approximate pin.",s:[["VWC",""],["PABL",""],["UPA",""]]},
{t:1,a:"SH",n:"Andrew Carnegie Free Library & Music Hall",ad:"300 Beechwood Ave, Carnegie",la:40.4090,ln:-80.0845,
 w:"One of only four libraries Andrew Carnegie personally endowed (1901), combining a working library with a restored concert and music hall on the National Register.",
 k:"Music hall hosts year-round shows. ~15 min southwest, in Carnegie borough. Approximate pin.",s:[["UPA",""],["TRIB",""]]},
{t:2,a:"SH",n:"Captain Thomas Espy G.A.R. Post (Civil War Room)",ad:"300 Beechwood Ave, Carnegie",la:40.4091,ln:-80.0846,
 w:"The best-preserved Grand Army of the Republic post in the country — a virtually untouched 1906 memorial room of ~2,000 Civil War artefacts, sealed for 50 years, inside the Carnegie library.",
 k:"Free tours Saturdays 11–3, or weekday appointment. Approximate pin.",s:[["UPA",""],["TRIB",""]]},
{t:2,a:"SH",n:"Uptown Mt. Lebanon business district",ad:"Washington Rd, Mt. Lebanon",la:40.3760,ln:-80.0490,
 w:"Mt. Lebanon's walkable central district of ~41 independent shops and restaurants along a recently-renovated streetscape, anchored by Clearview Common and reached by the 'T' light rail.",
 k:"Free; First Fridays, an Uptown farmers market and Artists' Market. Approximate pin.",s:[["ALM",""],["NP",""]]},
{t:2,a:"SH",n:"Dormont Pool",ad:"1801 Dormont Ave, Dormont",la:40.3945,ln:-80.0345,
 w:"One of Pennsylvania's largest and oldest municipal swimming pools (~1.85 acres), built up through the 1920s and dedicated in 1929 — a designated historic landmark.",
 k:"Seasonal (summer); set in 23.5-acre Dormont Park. Approximate pin.",warn:1,s:[["NP",""],["ALM",""]]},
{t:2,a:"SH",n:"Row House — Hollywood Theater",ad:"1449 Potomac Ave, Dormont",la:40.3940,ln:-80.0360,
 w:"A restored ~1926 atmospheric movie palace — domed ceiling with embedded star lights — reopened in November 2025 by Row House Cinema as Pittsburgh's largest full-time movie hall.",
 k:"Screens first-run and repertory film; check showtimes. Approximate pin.",s:[["NP",""],["TRIB",""]]},
{t:2,a:"SH",n:"LeMoyne House",ad:"49 E Maiden St, Washington, PA",la:40.1735,ln:-80.2455,
 w:"An 1812 stone house — Pennsylvania's first National Historic Landmark of the Underground Railroad — home of abolitionist Dr. F. Julius LeMoyne and now the Washington County Historical Society.",
 k:"Tours via the historical society; call ahead. ~40 min south. Approximate pin.",s:[["OBSREP",""],["VWC",""]]},
{t:2,a:"SH",n:"David Bradford House & Whiskey Rebellion Center",ad:"175 S Main St, Washington, PA",la:40.1720,ln:-80.2465,
 w:"The restored home of Whiskey Rebellion leader David Bradford, now a museum with an adjoining Whiskey Rebellion Education & Visitor Center in downtown Washington.",
 k:"Docent tours Wed–Sat, Apr–Nov; free (enter via the visitor center). Approximate pin.",s:[["VWC",""],["OBSREP",""]]},
{t:2,a:"SH",n:"Woodville Plantation (John & Presley Neville House)",ad:"1375 Washington Pike, Bridgeville",la:40.3560,ln:-80.1040,
 w:"A National Historic Landmark house that was a focal point of the 1794 Whiskey Rebellion, run as a house museum by the Pittsburgh History & Landmarks Foundation.",
 k:"House tours Sundays 1–4, late Mar–early Dec; grounds weekdays. Approximate pin.",s:[["PHLF",""],["DTB",""]]},
{t:2,a:"SH",n:"Mingo Creek County Park & the covered bridges",ad:"Mingo Creek County Park, Finleyville",la:40.1850,ln:-80.0400,
 w:"A 2,600-acre county park with two historic covered bridges — the picturesque Ebenezer and the 1841 Henry — a short walk apart, plus a creekside trail; Washington County has 23 covered bridges.",
 k:"Free, dawn to dusk. ~30 min south. Approximate pin.",s:[["DTB",""],["UPA",""]]},
{t:2,a:"SH",n:"Washington County Agricultural Fair",ad:"2151 N Main St, Washington, PA",la:40.1930,ln:-80.2440,
 w:"One of Pennsylvania's largest and oldest county fairs — livestock, carnival rides, live entertainment and fair food — on the Washington fairgrounds each August.",
 k:"Runs annually in mid-August; grounds host events year-round. Approximate pin.",warn:1,s:[["VWC",""],["OBSREP",""]]},
{t:3,a:"SH",n:"Duncan & Miller Glass Museum",ad:"525 Jefferson Ave, Washington, PA",la:40.1755,ln:-80.2420,
 w:"A museum of the celebrated Duncan & Miller glassware once made in Washington, PA, run by the National Duncan Glass Society.",
 k:"Thu–Sun 10–4, Mar–Dec, or by appointment. Approximate pin.",warn:1,s:[["VWC",""],["PABL",""]]},
{t:3,a:"SH",n:"Perry Como Statue",ad:"68 E Pike St, Canonsburg",la:40.2635,ln:-80.1875,
 w:"A bronze of crooner Perry Como, born in Canonsburg in 1912, in the walkable downtown — speakers by the borough building play his singing.",
 k:"Free roadside stop; pair with Sarris Candies nearby. Approximate pin.",s:[["VWC",""],["NP",""]]},
{t:3,a:"SH",n:"LeMoyne Crematory",ad:"Gallows Hill, North Franklin Twp",la:40.1800,ln:-80.2560,
 w:"The first crematory built in the United States (1876), where the first U.S. cremation took place that December — restored and on the National Register.",
 k:"Tours by appointment via the historical society; niche history. Approximate pin.",warn:1,s:[["OBSREP",""],["VWC",""]]},
{t:3,a:"SH",n:"Washington County Courthouse",ad:"1 S Main St, Washington, PA",la:40.1720,ln:-80.2470,
 w:"A 1900 Beaux-Arts landmark by Frederick Osterling, topped by a dome and a statue of George Washington, with a grand stair and a 40-foot stained-glass ceiling.",
 k:"Working courthouse; admire the exterior/lobby during business hours. Approximate pin.",s:[["OBSREP",""],["VWC",""]]},
{t:3,a:"SH",n:"Carnegie Stage & Main Street",ad:"25 W Main St, Carnegie",la:40.4085,ln:-80.0850,
 w:"An intimate professional theatre on Carnegie's revitalised, walkable Main Street of shops and antiques, with a monthly Carnegie Crawl.",
 k:"Performances generally Thu–Sun; check the schedule. Approximate pin.",s:[["NP",""],["TRIB",""]]},
{t:3,a:"SH",n:"Mingo Creek Park Observatory",ad:"1 Shelter 10 Rd, Finleyville",la:40.1970,ln:-80.0180,
 w:"The largest amateur observatory in southwestern PA, run by the Amateur Astronomers Association of Pittsburgh, hosting free public 'Star Parties' since 2005.",
 k:"Free star parties on set Fri/Sat evenings, weather permitting. Approximate pin.",warn:1,s:[["VWC",""],["DTB",""]]},
{t:3,a:"SH",n:"Little Lake Theatre",ad:"500 Lakeside Dr S, Canonsburg",la:40.2830,ln:-80.1560,
 w:"A historic theatre-in-the-round founded in 1949 in a former barn on Canonsburg Lake, staging comedies, dramas, classics and children's theatre in an intimate 180-seat setting.",
 k:"Check the season for the schedule. Approximate pin.",s:[["VWC",""],["NP",""]]},
{t:3,a:"SH",n:"Cross Creek County Park",ad:"near Avella, PA",la:40.2740,ln:-80.4030,
 w:"Washington County's largest park (2,000+ acres) centred on Cross Creek Lake for boating and fishing, with hiking trails, a bike park and picnic shelters.",
 k:"Free, dawn to dusk; PA Fish & Boat license to fish or boat. Approximate pin.",s:[["DTB",""],["VWC",""]]},
{t:3,a:"SH",n:"Washington & Jefferson College (McMillan Hall)",ad:"60 S Lincoln St, Washington, PA",la:40.1720,ln:-80.2440,
 w:"A historic walkable campus whose McMillan Hall (1793) is the oldest college building west of the Alleghenies, with the Olin Fine Arts Center for public performances.",
 k:"Campus open to stroll; Olin hosts a public season. Approximate pin.",s:[["VWC",""]]},
/* == EASTERN SUBURBS & RIVER VALLEYS == */
{t:1,a:"EV",n:"Carrie Blast Furnaces National Historic Landmark",ad:"801 Carrie Furnace Blvd, Rankin",la:40.4131,ln:-79.8901,
 w:"Furnaces #6 and #7 of the former U.S. Steel Homestead Works, towering 92 feet over the Monongahela — rare pre-WWII iron-making relics now toured by Rivers of Steel for industrial history and its famous guerrilla art.",
 k:"Guided Industrial and Arts & Grounds tours, May–Oct; book ahead. Approximate pin.",warn:1,s:[["ROS",""],["LP",""],["TA",""]]},
{t:1,a:"EV",n:"Pump House & Battle of Homestead Site",ad:"880 E Waterfront Dr, Munhall",la:40.4090,ln:-79.9080,
 w:"The 1892 Carnegie Steel pump house where the Battle of Homestead between Pinkertons and steelworkers left ten dead — a National Historic Landmark of American labour history.",
 k:"Grounds free, trailside on the GAP; interior tours via Rivers of Steel and the Battle of Homestead Foundation. Approximate pin.",s:[["ROS",""],["BOH",""]]},
{t:2,a:"EV",n:"Braddock Carnegie Library",ad:"419 Library St, Braddock",la:40.4030,ln:-79.8690,
 w:"The first Carnegie library in the United States, dedicated by Andrew Carnegie in 1889 — a National Historic Landmark saved from demolition and restored, with an original music hall and gym.",
 k:"Free; recently completed a major restoration. Approximate pin.",s:[["ROS",""],["DTB",""]]},
{t:2,a:"EV",n:"Carnegie Library of Homestead Music Hall",ad:"510 E 10th Ave, Munhall",la:40.4040,ln:-79.9010,
 w:"An 1898 Carnegie library and 1,047-seat music hall — the oldest Carnegie library in continuous operation in its original building — and a busy live-concert venue.",
 k:"Library free to browse; music-hall shows ticketed. Approximate pin.",s:[["ROS",""],["VP",""]]},
{t:2,a:"EV",n:"Bost Building (Rivers of Steel Visitor Center)",ad:"623 E 8th Ave, Homestead",la:40.4055,ln:-79.9130,
 w:"The 1892 hotel that served as strike headquarters for the steelworkers' union during the Homestead Lockout — now a National Historic Landmark museum and Rivers of Steel's visitor center.",
 k:"Galleries on the Homestead Works and the 1892 strike; check hours. Approximate pin.",s:[["ROS",""]]},
{t:2,a:"EV",n:"The Waterfront & the Homestead stacks",ad:"E Waterfront Dr, Homestead",la:40.4070,ln:-79.9120,
 w:"An open-air shopping district built on the former U.S. Steel Homestead Works, preserving a row of twelve tall brick stacks, a gantry crane and the pump house as reminders of the mill.",
 k:"Free public access; a short walk from the Pump House and the GAP. Approximate pin.",s:[["VP",""],["DTB",""]]},
{t:2,a:"EV",n:"Monroeville Mall & the Living Dead Museum",ad:"200 Mall Circle Dr, Monroeville",la:40.4270,ln:-79.7620,
 w:"The 1969 mall used as the primary filming location for George Romero's 1978 'Dawn of the Dead', with a Romero bust, 'Romero Court' and the Living Dead Museum shrine to the film.",
 k:"Museum on the upper level; annual Living Dead Weekend in June. Mall's future uncertain. Approximate pin.",warn:1,s:[["NP",""],["TA",""]]},
{t:2,a:"EV",n:"Boyce Park",ad:"675 Old Frankstown Rd, Plum",la:40.4550,ln:-79.7250,
 w:"A 1,096-acre Allegheny County park spanning Monroeville and Plum — the only place in the county with downhill skiing and snowtubing lifts, plus a summer wave pool, nature center and trails.",
 k:"Free entry; ski area and wave pool are seasonal and paid. Approximate pin.",s:[["ACP",""],["DTB",""]]},
{t:2,a:"EV",n:"Aspinwall Riverfront Park",ad:"285 River Ave, Aspinwall",la:40.4920,ln:-79.9010,
 w:"A free riverfront park on a reclaimed industrial site with an easy Highmark Trail loop, a kayak launch and a playground on the Allegheny — expanding along the old Brilliant Line rail corridor.",
 k:"Free, dawn to dusk. Approximate pin.",s:[["NP",""]]},
{t:2,a:"EV",n:"Beechwood Farms Nature Reserve",ad:"614 Dorseyville Rd, Fox Chapel",la:40.5290,ln:-79.8940,
 w:"A 134-acre Audubon nature reserve — one of the region's largest private preserves — with forest and meadow trails, a nature store and native-plant center, and the regional Audubon headquarters.",
 k:"Trails free, dawn to dusk; no pets. Approximate pin.",s:[["AUD",""],["DTB",""]]},
{t:2,a:"EV",n:"Braddock's Battlefield History Center",ad:"609 6th St, Braddock",la:40.4030,ln:-79.8640,
 w:"A museum interpreting the 1755 Battle of the Monongahela — General Braddock's defeat, with a young George Washington present — on the edge of the actual battlefield.",
 k:"Seasonal weekend hours (roughly May–Aug). Approximate pin.",warn:1,s:[["VP",""]]},
{t:2,a:"EV",n:"Tour-Ed Mine & Museum",ad:"748 Bull Creek Rd, Tarentum",la:40.6100,ln:-79.7600,
 w:"A real former coal mine turned museum where visitors ride a mantrip a half-mile underground, plus 13 acres of mining and farm exhibits, a 1785 log home and a caboose.",
 k:"Memorial Day–Labor Day, daily 10–4, closed Tuesdays; cash only. ~30 min north. Approximate pin.",warn:1,s:[["TRIB",""],["DTB",""]]},
{t:2,a:"EV",n:"Oakmont Country Club",ad:"1233 Hulton Rd, Oakmont",la:40.5250,ln:-79.8330,
 w:"The private championship course that has hosted a record ten U.S. Opens (most recently 2025) and 18 USGA championships — one of the most storied courses in the world.",
 k:"Private; visitable only during USGA championship spectator events. Approximate pin.",warn:1,s:[["NP",""],["VP",""]]},
{t:2,a:"EV",n:"Duff Park",ad:"Old William Penn Hwy, Murrysville",la:40.4300,ln:-79.6800,
 w:"A 237-acre park with one of only three remaining old-growth deciduous forests in Pennsylvania — oaks 250–300 years old — a state Wild Plant Sanctuary famous for spring wildflowers.",
 k:"Free; connects to the Westmoreland Heritage Trail. Approximate pin.",s:[["DTB",""]]},
{t:3,a:"EV",n:"Sandcastle Waterpark",ad:"1000 Sandcastle Dr, West Homestead",la:40.4020,ln:-79.9180,
 w:"A 67-acre Monongahela riverside water park (opened 1989) with sixteen slides, a wave pool and a lazy river, on the old Homestead Works land beside the Waterfront.",
 k:"Seasonal summer; paid admission. Approximate pin.",warn:1,s:[["VP",""]]},
{t:3,a:"EV",n:"Dead Man's Hollow Conservation Area",ad:"near the GAP Boston trailhead, McKeesport",la:40.3450,ln:-79.8300,
 w:"A 450-acre Allegheny Land Trust preserve along the Youghiogheny with 8+ miles of trails past a waterfall, an 'enchanted staircase' and overgrown quarry and pipe-factory ruins.",
 k:"Free; main access ~3/4 mile from the GAP's Boston parking lot. Approximate pin.",s:[["DTB",""]]},
{t:3,a:"EV",n:"Round Hill Park",ad:"651 Round Hill Rd, Elizabeth",la:40.2550,ln:-79.8600,
 w:"A 1,101-acre county park built around a working demonstration farm — a dairy barn, animals, herb gardens and retired county horses — plus a spray park and trails.",
 k:"Free; the exhibit farm is open daily year-round. Approximate pin.",s:[["ACP",""],["DTB",""]]},
{t:3,a:"EV",n:"Renziehausen Park Rose Garden & Arboretum",ad:"1400 Pinoak Dr, McKeesport",la:40.3520,ln:-79.8280,
 w:"A 205-acre city park whose rose garden holds ~1,200 bushes in 28 beds — the second-largest rose garden in Pennsylvania after Hershey — with an arboretum and bandshell.",
 k:"Free, open daily; roses best in summer. Approximate pin.",s:[["DTB",""]]},
{t:3,a:"EV",n:"McKees Rocks Mound",ad:"near Chartiers Creek & the Ohio, McKees Rocks",la:40.4720,ln:-80.0640,
 w:"The remnant of what was western Pennsylvania's largest Native American burial mound, built by the Adena people ~200 BC and later used by the Hopewell — largely quarried away, now marked by a state marker.",
 k:"A historical marker; the mound itself is mostly gone. Approximate pin.",s:[["DTB",""]]},
{t:3,a:"EV",n:"Monroeville Convention Center",ad:"209 Mall Plaza Blvd, Monroeville",la:40.4280,ln:-79.7600,
 w:"A 100,000-square-foot event hall east of the city, best known to visitors as the home of Steel City Con and large train, toy and craft shows.",
 k:"Visit-worthy chiefly during ticketed shows; check the calendar. Approximate pin.",warn:1,s:[["VP",""]]},
/* == DAY TRIPS & THE LAUREL HIGHLANDS == */
{t:1,a:"DY",n:"Fallingwater",ad:"1491 Mill Run Rd, Mill Run, PA",la:39.9064,ln:-79.4681,
 w:"Frank Lloyd Wright's masterpiece cantilevered over a waterfall in the Laurel Highlands — arguably the most famous house in America, and worth every mile of the drive.",
 k:"Timed tickets, reserve well ahead; closed Wednesdays and winter weekdays. ~90 min southeast.",s:[["AO",""],["VP",""],["LP",""]]},
{t:1,a:"DY",n:"Kennywood",ad:"4800 Kennywood Blvd, West Mifflin, PA",la:40.3870,ln:-79.8620,
 w:"A beloved 1898 amusement park and National Historic Landmark — wooden coasters (Jack Rabbit, Thunderbolt, Racer), Noah's Ark and Potato Patch fries — old-school in the best way.",
 k:"Seasonal (summer + Phantom Fright Nights). ~20 min southeast. Buy ahead.",warn:1,s:[["VP",""],["LP",""]]},
{t:2,a:"DY",n:"Ohiopyle State Park",ad:"Ohiopyle, PA (Laurel Highlands)",la:39.8690,ln:-79.4930,
 w:"Whitewater on the Youghiogheny, waterfalls, the Great Allegheny Passage trail and Cucumber Falls — the outdoor heart of the Laurel Highlands, near Fallingwater.",
 k:"Free park; rafting outfitters and bike rentals in town. ~90 min southeast.",s:[["UPA",""],["VP",""]]},
{t:2,a:"DY",n:"Kentuck Knob",ad:"723 Kentuck Rd, Chalk Hill, PA",la:39.8790,ln:-79.4700,
 w:"A second, quieter Frank Lloyd Wright house near Fallingwater — a hexagon-grid Usonian home with a sculpture meadow — often paired with Fallingwater in one Laurel Highlands day.",
 k:"Timed tours; reserve ahead. ~90 min southeast; combine with Fallingwater.",s:[["UPA",""],["AO",""]]},
{t:3,a:"DY",n:"Idlewild & SoakZone",ad:"2574 Rt 30, Ligonier, PA",la:40.2470,ln:-79.1900,
 w:"A gentle 1878 park in Ligonier repeatedly voted among the best kids' amusement parks in the world — home to Mister Rogers' Neighborhood of Make-Believe trolley ride.",
 k:"Seasonal (summer). ~1 hr east. Great for younger kids. Approximate pin.",warn:1,s:[["UPA",""],["VP",""]]},
{t:3,a:"DY",n:"Bayernhof Music Museum",ad:"225 St Charles Pl, O'Hara Township",la:40.5150,ln:-79.8760,
 w:"An eccentric hilltop mansion stuffed with rare automatic music machines — orchestrions, music boxes, a hidden bar and a cave — shown only by guided tour.",
 k:"Guided tours by reservation only; not for small kids. ~20 min northeast. Approximate pin.",warn:1,s:[["AO",""]]},
{t:3,a:"DY",n:"Meadowcroft Rockshelter",ad:"401 Meadowcroft Rd, Avella, PA",la:40.2650,ln:-80.4830,
 w:"A National Historic Landmark rock overhang with evidence of human use going back some 19,000 years — among the oldest sites of habitation in North America — with a re-created 16th-century village.",
 k:"Seasonal hours; guided. ~50 min west. A genuine deep-history stop. Approximate pin.",warn:1,s:[["UPA",""],["AO",""]]}
];

const FS = {
  AO:{k:"ATLAS OBSCURA",t:"Atlas Obscura — Pittsburgh",u:"https://www.atlasobscura.com/things-to-do/pittsburgh-pennsylvania",l:"Atlas Obscura"},
  VP:{k:"VISIT PITTSBURGH",t:"Visit Pittsburgh — food, drink & markets",u:"https://www.visitpittsburgh.com/restaurants-culinary/",l:"Visit Pittsburgh"},
  GFP:{k:"GOOD FOOD PGH",t:"Good Food Pittsburgh",u:"https://goodfoodpittsburgh.com",l:"Good Food Pittsburgh"},
  DTB:{k:"DISCOVER BURGH",t:"Discover the Burgh — Best Restaurants in Pittsburgh",u:"https://www.discovertheburgh.com/best-restaurants-in-pittsburgh/",l:"Discover the Burgh"},
  PGHMAG:{k:"PITTSBURGH MAG",t:"Pittsburgh Magazine — The Best Restaurants in Pittsburgh",u:"https://www.pittsburghmagazine.com/here-are-the-25-best-restaurants-in-pittsburgh/",l:"Pittsburgh Magazine"},
  PGPG:{k:"POST-GAZETTE",t:"Pittsburgh Post-Gazette — Best restaurants",u:"https://newsinteractive.post-gazette.com/pittsburgh-best-restaurants-2025/",l:"Post-Gazette"},
  CP:{k:"CITY PAPER",t:"Pittsburgh City Paper — Best Of Readers' Poll",u:"https://www.pghcitypaper.com/food-drink/",l:"Pittsburgh City Paper"},
  USN:{k:"U.S. NEWS",t:"U.S. News Travel — Best Things to Do in Pittsburgh",u:"https://travel.usnews.com/Pittsburgh_PA/Things_To_Do/",l:"U.S. News Travel"},
  TT:{k:"TASTING TABLE",t:"Tasting Table — Pittsburgh features",u:"https://www.tastingtable.com/",l:"Tasting Table"},
  SAV:{k:"SAVEUR",t:"Saveur — America's Next Great Chinatown Takes Root in Pittsburgh",u:"https://www.saveur.com/how-pittsburgh-is-growing-americas-next-chinatown-chinese-restaurants",l:"Saveur"},
  INF:{k:"INFATUATION",t:"The Infatuation — Pittsburgh",u:"https://www.theinfatuation.com/pittsburgh",l:"The Infatuation"},
  FR:{k:"FOOD REPUBLIC",t:"Food Republic — the Original Oyster House",u:"https://www.foodrepublic.com/2080475/original-oyster-house-fried-fish-sandwiches-pittsburgh/",l:"Food Republic"},
  NP:{k:"NEXTPITTSBURGH",t:"NextPittsburgh — ice cream, markets & dining",u:"https://nextpittsburgh.com",l:"NextPittsburgh"},
  KB:{k:"KIDSBURGH",t:"Kidsburgh — farm festivals & u-pick",u:"https://www.kidsburgh.org/pick-perfect-pumpkin-10-pittsburgh-farm-festivals/",l:"Kidsburgh"},
  VWC:{k:"VISIT WASH. CO",t:"Visit Washington County PA",u:"https://www.visitwashingtoncountypa.com/",l:"Visit Washington County"},
  AXIOS:{k:"AXIOS PGH",t:"Axios Pittsburgh — apple picking",u:"https://www.axios.com/local/pittsburgh",l:"Axios Pittsburgh"},
  FADD:{k:"ADDED",t:"Local staples added from general knowledge",u:"",l:"My addition — verify before visiting"}
};

const CUISINES = [
  {id:"AM",  n:"Pittsburgh Classics"},
  {id:"IT",  n:"Italian"},
  {id:"POL", n:"Polish & Pierogi"},
  {id:"AS",  n:"Asian & Dumplings"},
  {id:"ME",  n:"Middle Eastern"},
  {id:"LAT", n:"Latin American"},
  {id:"CAF", n:"Cafe & Coffee"},
  {id:"DES", n:"Dessert & Bakery"},
  {id:"DR",  n:"Drinks & Breweries"},
  {id:"MKT", n:"Markets"},
  {id:"FARM",n:"Farms & U-Pick"}
];

const F = [
{t:1,a:"DT",cz:["AM"],n:"Primanti Bros (original)",ad:"46 18th St, Strip District",la:40.4500,ln:-79.9760,
 w:"The 1933 Strip original of a Pittsburgh institution. The sandwich: grilled meat, provolone, oil-and-vinegar slaw and fries all stacked inside the Italian bread. Order it as-is.",
 k:"Open late; cash and cards. The other locations are fine, but this is the one.",s:[["VP",""],["DTB",""]]},
{t:1,a:"DT",cz:["AM"],n:"The Original Oyster House",ad:"20 Market Sq, Downtown",la:40.4409,ln:-80.0020,
 w:"Pittsburgh's oldest bar and restaurant (1870), a historic landmark, famous for a giant breaded fish sandwich and breaded oysters from the original Mary Americus recipe.",
 k:"Walk-in; old-school counter, cash-friendly. A landmark, not just a meal.",s:[["FR",""],["CP",""],["VP",""]]},
{t:1,a:"OAK",cz:["AM"],n:"Tessaro's",ad:"4601 Liberty Ave, Bloomfield",la:40.4620,ln:-79.9490,
 w:"Since 1985, in-house-ground burgers cooked over local hardwood coals on a cast-iron grill — voted the city's Best Burger by Pittsburgh Magazine readers.",
 k:"Popular; the hardwood grill is the whole point. Approximate pin.",s:[["DTB",""],["PGHMAG",""]]},
{t:2,a:"DT",cz:["CAF","AM"],n:"Pamela's Diner (Strip)",ad:"60 21st St, Strip District",la:40.4510,ln:-79.9750,
 w:"The classic Pittsburgh breakfast: crepe-thin, crispy-edged 'hotcakes' rolled around fruit or chocolate. Obama liked them enough to fly the cooks to the White House.",
 k:"Cash only at some locations; breakfast/brunch. Expect a wait on weekends.",s:[["GFP",""],["DTB",""]]},
{t:3,a:"OAK",cz:["AM"],n:"The Original Hot Dog Shop \u2014 CLOSED",ad:"3901 Forbes Ave, Oakland",la:40.4425,ln:-79.9600,
 w:"'The O' — a beloved, grubby Oakland institution since 1960 famous for a mountain of fresh-cut fries with every order and cheap beer, feeding Pitt students at 2am.",
 k:"CLOSED April 2020 (Covid), never reopened \u2014 the O\u2019s corner at Forbes &amp; Bouquet is now other restaurants. Kept for the record.",warn:1,s:[["FADD",""],["CP",""]]},
{t:2,a:"DT",cz:["AM","IT"],n:"Gaucho Parrilla Argentina",ad:"1601 Penn Ave, Strip District",la:40.4520,ln:-79.9880,
 w:"Wood-fired Argentine grill that repeatedly tops the city's best-restaurant lists — chimichurri-slathered meats and vegetables off open flame, in a line-out-the-door Strip room.",
 k:"Counter-service but destination-worthy; peak-time lines. Approximate pin.",s:[["DTB",""],["GFP",""]]},
{t:2,a:"OAK",cz:["AM"],n:"Morcilla",ad:"3519 Butler St, Lawrenceville",la:40.4700,ln:-79.9600,
 w:"A James Beard–winning Spanish restaurant in Lawrenceville — pintxos, house-cured charcuterie and its namesake blood sausage — routinely called one of the best in the country.",
 k:"Reserve ahead; small plates add up. Approximate pin.",s:[["GFP",""],["PGHMAG",""],["PGPG",""]]},
{t:2,a:"EV",cz:["AM"],n:"Superior Motors \u2014 CLOSED",ad:"1211 Braddock Ave, Braddock",la:40.4030,ln:-79.8690,
 w:"Chef Kevin Sousa's acclaimed farm-to-table room in a former Braddock car dealership, in the shadow of the still-running Edgar Thomson steelworks — a national dining story.",
 k:"CLOSED \u2014 shut at the start of the 2020 pandemic and never reopened; a Brew Gentlemen brewpub is taking the Braddock space. Kept for the record.",warn:1,s:[["GFP",""],["PGHMAG",""]]},
{t:2,a:"OAK",cz:["AM"],n:"Kelly's Bar & Lounge",ad:"6012 Centre Ave, East Liberty",la:40.4600,ln:-79.9250,
 w:"A classic dive with a creative cocktail list and a baked-to-order mac and cheese widely cited as the city's best.",
 k:"The mac takes ~20 minutes to bake; $4 daily cocktail special. Approximate pin.",s:[["INF",""],["PGHMAG",""]]},
{t:1,a:"OAK",cz:["POL"],n:"Apteka",ad:"4606 Penn Ave, Bloomfield",la:40.4640,ln:-79.9500,
 w:"A nationally celebrated, James Beard–nominated Central-and-Eastern-European kitchen that happens to be entirely vegan — pierogi, cabbage and rye done with real craft.",
 k:"Very popular; go early or expect a wait. Approximate pin.",s:[["GFP",""],["PGHMAG",""]]},
{t:2,a:"DT",cz:["POL"],n:"Pierogies Plus",ad:"342 Island Ave, McKees Rocks",la:40.4700,ln:-80.0640,
 w:"A former gas station where Polish women hand-pinch pierogi daily — the benchmark for Pittsburgh's signature dumpling, boiled or fried with butter and onions.",
 k:"Takeout-leaning; cash-friendly. ~15 min from downtown. Approximate pin.",s:[["GFP",""],["VP",""]]},
{t:2,a:"OAK",cz:["POL"],n:"Gooski's",ad:"3117 Brereton St, Polish Hill",la:40.4560,ln:-79.9560,
 w:"A punk dive bar on Polish Hill making house pierogies and a kielbasa-'n'-kraut sandwich — a Thrillist best-dive-bars pick with a jukebox to match.",
 k:"Cash only; kitchen evenings only. Approximate pin.",warn:1,s:[["GFP",""],["DTB",""]]},
{t:3,a:"DT",cz:["POL"],n:"S&D Polish Deli",ad:"2204 Penn Ave, Strip District",la:40.4510,ln:-79.9770,
 w:"A tiny Strip District deli for kielbasa, stuffed cabbage and pierogi to eat in or take home — Old-World Polish cooking with no frills.",
 k:"Small; lunch-focused. Approximate pin.",s:[["VP",""]]},
{t:1,a:"OAK",cz:["AS"],n:"Everyday Noodles",ad:"5875 Forbes Ave, Squirrel Hill",la:40.4380,ln:-79.9230,
 w:"The place that brought xiao long bao to Pittsburgh in 2013 — pork soup dumplings and hand-pulled noodles made in the front window.",
 k:"Popular; watch the dumpling-folding. Approximate pin.",s:[["PGHMAG",""],["VP",""],["SAV",""]]},
{t:1,a:"OAK",cz:["AS"],n:"Chengdu Gourmet",ad:"5840 Forward Ave, Squirrel Hill",la:40.4340,ln:-79.9220,
 w:"Four-time James Beard semifinalist chef Wei Zhu's Sichuan kitchen — mapo tofu and double-cooked pork belly numbing with Sichuan peppercorns.",
 k:"Order from the secondary Sichuan menu. Approximate pin.",s:[["SAV",""],["CP",""],["PGPG",""]]},
{t:2,a:"OAK",cz:["AS"],n:"How Lee",ad:"5888 Forbes Ave, Squirrel Hill",la:40.4380,ln:-79.9230,
 w:"A bilingual-menu Sichuan spot favoured by Chinese-speaking regulars — Chongqing dry hot chicken and dan dan noodles.",
 k:"Casual; go for the Sichuan menu. Approximate pin.",s:[["SAV",""],["DTB",""]]},
{t:2,a:"OAK",cz:["AS"],n:"KIIN Lao & Thai Eatery",ad:"5846 Forbes Ave, Squirrel Hill",la:40.4380,ln:-79.9230,
 w:"Pittsburgh's first Lao restaurant (in the old Bangkok Balcony space) — chicken larb with sticky rice and Isan-style Thai dishes.",
 k:"Reservations help on weekends. Approximate pin.",s:[["PGHMAG",""],["CP",""]]},
{t:1,a:"SS",cz:["ME"],n:"Salem's Market & Grill",ad:"2923 Penn Ave, Strip District",la:40.4560,ln:-79.9680,
 w:"Pittsburgh's premier halal butcher and Middle Eastern grill — shawarma and kabobs off the grill and Indo-Pak steam-tray dishes, with a full international market attached.",
 k:"Also a grocery/halal meat market. Approximate pin.",s:[["PGHMAG",""],["CP",""],["DTB",""]]},
{t:2,a:"SS",cz:["ME"],n:"Kassab's",ad:"1207 E Carson St, South Side",la:40.4285,ln:-79.9800,
 w:"A longtime Lebanese kitchen on the South Side — award-winning falafel and a big, cheap lamb shank, plus kebabs and shawarma.",
 k:"Closed Sundays. Approximate pin.",s:[["CP",""],["DTB",""]]},
{t:3,a:"EV",cz:["LAT"],n:"Rey Azteca",ad:"3448 William Penn Hwy, Monroeville",la:40.4270,ln:-79.7620,
 w:"A suburban favourite for authentic Mexican — carne asada street tacos and tableside guacamole.",
 k:"Several east-suburb locations. Approximate pin.",s:[["DTB",""]]},
{t:1,a:"SS",cz:["IT"],n:"Fiori's Pizzaria",ad:"103 Wenzell Ave, Brookline",la:40.3960,ln:-80.0230,
 w:"A Brookline staple since 1979 whose hand-tossed cuts have won City Paper's Best Pizza readers' poll every year since 2019.",
 k:"Casual; grab a cut. Approximate pin.",s:[["CP",""],["DTB",""]]},
{t:1,a:"SS",cz:["IT"],n:"Alla Famiglia",ad:"804 E Warrington Ave, Allentown",la:40.4180,ln:-79.9950,
 w:"An old-world fine-dining Italian in Allentown since 1997 — the house specialty is veal, especially the Veal Milanese, in a multi-course family-style meal.",
 k:"Expensive; reservations recommended. Approximate pin.",s:[["DTB",""],["PGHMAG",""]]},
{t:2,a:"OAK",cz:["IT"],n:"DiAnoia's Eatery",ad:"2549 Penn Ave, Strip District",la:40.4540,ln:-79.9730,
 w:"A modern Italian favourite for house pastas and a proper breakfast pastry case — one of the restaurants that put the new Strip on the national map.",
 k:"Popular brunch and dinner; reservations help. Approximate pin.",s:[["GFP",""],["PGHMAG",""]]},
{t:2,a:"OAK",cz:["IT"],n:"Piccolo Forno",ad:"3801 Butler St, Lawrenceville",la:40.4710,ln:-79.9610,
 w:"A Tuscan trattoria since 2005 — Carla Branduzzi's dozen hand-made pastas and gnocchi, with lasagna the signature.",
 k:"BYOB; small dining room. Approximate pin.",s:[["PGHMAG",""],["DTB",""]]},
{t:2,a:"OAK",cz:["IT"],n:"Driftwood Oven",ad:"3615 Butler St, Lawrenceville",la:40.4700,ln:-79.9615,
 w:"An artisan sourdough pizzeria — naturally-leavened Grandma-style square pies plus 16-inch thin rounds.",
 k:"Casual; the square is the move. Approximate pin.",s:[["PGHMAG",""],["DTB",""]]},
{t:3,a:"OAK",cz:["IT"],n:"Mineo's Pizza House",ad:"2128 Murray Ave, Squirrel Hill",la:40.4330,ln:-79.9230,
 w:"Half of Squirrel Hill's decades-old Mineo's-vs-Aiello's pizza rivalry — a thick, cheese-heavy Pittsburgh-style pie locals argue about with real feeling.",
 k:"Casual; grab a slice and judge it against Aiello's up the street.",s:[["GFP",""]]},
{t:3,a:"OAK",cz:["IT"],n:"Aiello's Pizza",ad:"2112 Murray Ave, Squirrel Hill",la:40.4331,ln:-79.9232,
 w:"The other half of the legendary Squirrel Hill rivalry, six doors from Mineo's — crisp thin-crust cuts with a devoted camp of its own.",
 k:"Casual; do the taste test. Approximate pin.",s:[["PGHMAG",""],["DTB",""]]},
{t:2,a:"EV",cz:["IT"],n:"Vincent's Pizza Park",ad:"998 Ardmore Blvd, Forest Hills",la:40.4180,ln:-79.8560,
 w:"A Forest Hills institution since 1952 — the overloaded mushroom 'Vinnie Pie', with pizzas so big a medium rivals other places' large.",
 k:"Cash only; long waits. Approximate pin.",warn:1,s:[["DTB",""]]},
{t:3,a:"DT",cz:["IT"],n:"Papa J's Twin Plaza",ad:"2200 Penn Ave, Strip District",la:40.4515,ln:-79.9790,
 w:"A revived Italian kitchen in the Strip — veal meatballs in marinara and two-day-proofed Roman-style pizza.",
 k:"The Carnegie original is closed; this is the Strip relocation. Approximate pin.",s:[["CP",""]]},
{t:2,a:"DT",cz:["CAF","AM"],n:"De Luca's Diner",ad:"2015 Penn Ave, Strip District",la:40.4515,ln:-79.9800,
 w:"A Strip District breakfast institution slinging enormous omelettes and hotcakes to a weekend line down the block — old-school diner energy at full volume.",
 k:"Cash-friendly; weekend waits. Breakfast/lunch. Approximate pin.",s:[["GFP",""]]},
{t:3,a:"DT",cz:["CAF"],n:"La Prima Espresso",ad:"205 21st St, Strip District",la:40.4510,ln:-79.9820,
 w:"An old-school Italian espresso bar in the Strip where the men play cards in the back and the espresso is the real thing — a Pittsburgh coffee landmark.",
 k:"Cash; standing-room mornings. Approximate pin.",s:[["NP",""]]},
{t:3,a:"OAK",cz:["CAF"],n:"Commonplace Coffee",ad:"5827 Forbes Ave, Squirrel Hill",la:40.4380,ln:-79.9235,
 w:"An iconic local roaster since 2003 with cosy neighbourhood cafés — house-roasted single-origin espresso.",
 k:"Several café locations. Approximate pin.",s:[["GFP",""]]},
{t:3,a:"DT",cz:["CAF"],n:"De Fer Coffee & Tea",ad:"2002 Smallman St, Strip District",la:40.4505,ln:-79.9810,
 w:"An employee-owned Strip roastery (2017) — house-roasted coffee and creative drinks like the espresso tonic — in an airy former warehouse.",
 k:"Spacious; good for working. Approximate pin.",s:[["GFP",""]]},
{t:1,a:"OAK",cz:["DES"],n:"Prantl's Bakery",ad:"5525 Walnut St, Shadyside",la:40.4530,ln:-79.9340,
 w:"Home of the Burnt Almond Torte — once called 'the greatest cake in America' — a yellow cake with custard and caramelised almonds that Pittsburghers ship across the country.",
 k:"Get a slice or a whole torte; also a Downtown shop. Approximate pin.",s:[["GFP",""],["PGHMAG",""]]},
{t:1,a:"EV",cz:["DES"],n:"Oakmont Bakery",ad:"1 Sweet St, Oakmont",la:40.5230,ln:-79.8380,
 w:"An enormous, beloved bakery (founded 1988) — one of the largest retail bakeries in America — whose burnt-almond torte, cookie-table trays and pepperoni rolls draw lines out the door.",
 k:"Huge cases; go early on weekends. ~20 min northeast. Approximate pin.",s:[["DTB",""],["PGHMAG",""],["NP",""]]},
{t:2,a:"SH",cz:["DES"],n:"Sarris Candies",ad:"511 Adams Ave, Canonsburg",la:40.2630,ln:-80.1870,
 w:"A regional chocolatier since 1960 with a 1,500-pound edible chocolate castle and an old-fashioned parlour famous for sundaes capped in hardened poured chocolate.",
 k:"Parlour open late; ~18 mi southwest in Canonsburg. Approximate pin.",s:[["DTB",""],["VWC",""]]},
{t:2,a:"DT",cz:["DES","CAF"],n:"Klavon's Ice Cream Parlor \u2014 CLOSED",ad:"2801 Penn Ave, Strip District",la:40.4560,ln:-79.9700,
 w:"A 1923 soda fountain restored to its original marble-and-mahogany glory in the Strip — sundaes, egg creams and banana splits in a genuine time capsule.",
 k:"Seasonal-ish hours; great with kids. Approximate pin.",s:[["VP",""],["NP",""]]},
{t:2,a:"OAK",cz:["DES"],n:"Gaby et Jules",ad:"5837 Forbes Ave, Squirrel Hill",la:40.4380,ln:-79.9236,
 w:"A French patisserie from Master Pastry Chef David Piquard — jewel-like macarons and rum canelés — the sweet anchor of Squirrel Hill's Forbes Avenue.",
 k:"Grab a box of macarons. Approximate pin.",s:[["PGHMAG",""],["NP",""]]},
{t:2,a:"OAK",cz:["DES"],n:"La Gourmandine",ad:"4605 Butler St, Lawrenceville",la:40.4720,ln:-79.9610,
 w:"A from-scratch French bakery (2010) — all-butter croissants and baguettes, plus quiches and tarts — with several locations across the city.",
 k:"Mornings for the best pastry selection. Approximate pin.",s:[["NP",""],["DTB",""]]},
{t:2,a:"DT",cz:["DES"],n:"Mancini's Bakery",ad:"1717 Penn Ave (Strip retail)",la:40.4500,ln:-79.9780,
 w:"Baking since 1926 — some 10,000 loaves a day — famous for a hand-rolled Italian 'twist' bread and fast-selling pepperoni rolls.",
 k:"Original bakery in McKees Rocks is 24/7; retail shop in the Strip. Approximate pin.",s:[["TT",""],["NP",""]]},
{t:2,a:"OAK",cz:["DES"],n:"Dave & Andy's Homemade Ice Cream",ad:"207 Atwood St, Oakland",la:40.4420,ln:-79.9570,
 w:"An Oakland institution since 1983 — hand-rolled waffle cones made on-site with an M&M plugged in the tip so nothing drips out.",
 k:"Cash-friendly; summer lines. Approximate pin.",s:[["PGHMAG",""],["NP",""]]},
{t:3,a:"SS",cz:["DES"],n:"Page Dairy Mart",ad:"4112 E Carson St, South Side",la:40.4270,ln:-79.9660,
 w:"A seasonal walk-up soft-serve stand by the river that opens every spring to long, happy lines — a South Side rite of warm weather since 1951.",
 k:"Cash; open spring–fall only. Cones and Gobs. Approximate pin.",warn:1,s:[["GFP",""]]},
{t:3,a:"OAK",cz:["DES"],n:"Millie's Homemade Ice Cream",ad:"232 S Highland Ave, Shadyside",la:40.4550,ln:-79.9250,
 w:"A beloved small-batch scoop shop (with a cult 'honey lavender') that grew from a farmers'-market stand into several East End parlours.",
 k:"Seasonal flavours; lines in summer. Approximate pin.",s:[["GFP",""],["NP",""]]},
{t:3,a:"DT",cz:["DES"],n:"Gus and Yia Yia's",ad:"Allegheny Commons Park, North Side",la:40.4560,ln:-80.0080,
 w:"A seasonal cart on the same North Side spot since 1934 — hand-shaved ice balls in syrup, plus peanuts and popcorn — with an honorary 'Gus & YiaYia Way' named for it.",
 k:"Seasonal cart (warm months), cash. Approximate pin.",warn:1,s:[["NP",""],["PGHMAG",""]]},
{t:3,a:"DT",cz:["DES","CAF"],n:"Enrico Biscotti",ad:"2022 Penn Ave, Strip District",la:40.4515,ln:-79.9790,
 w:"A hole-in-the-wall Strip bakery-café turning out biscotti and rustic breads from an old brick oven, with a hidden courtyard café out back.",
 k:"Small; mornings best. Approximate pin.",s:[["VP",""]]},
{t:1,a:"OAK",cz:["DR","AM"],n:"Church Brew Works",ad:"3525 Liberty Ave, Lawrenceville",la:40.4660,ln:-79.9600,
 w:"A brewery inside a magnificently restored 1902 Catholic church — brew tanks on the old altar, pierogi and house lagers under the stained glass. An only-in-Pittsburgh night out.",
 k:"Restaurant + brewery; busy on weekends. Approximate pin.",s:[["AO",""],["VP",""]]},
{t:1,a:"DT",cz:["DR"],n:"Wigle Whiskey",ad:"2401 Smallman St, Strip District",la:40.4525,ln:-79.9820,
 w:"Pittsburgh's first distillery since Prohibition and one of the most-awarded craft distilleries in the country — hand-milled local grain, copper-pot whiskey and a Strip tasting room named for a whiskey-rebellion figure.",
 k:"Tastings and tours; buy a bottle. Approximate pin.",s:[["VP",""],["PGHMAG",""]]},
{t:2,a:"OAK",cz:["DR"],n:"East End Brewing Company",ad:"147 Julius St, Larimer",la:40.4640,ln:-79.9080,
 w:"A pioneer of Pittsburgh craft beer with a big Larimer taproom — ~14 taps, pinball, food trucks and easy parking — a proper neighbourhood beer hall.",
 k:"Family/dog-friendly; food trucks. Approximate pin.",s:[["NP",""]]},
{t:3,a:"OAK",cz:["DR"],n:"Arsenal Cider House",ad:"300 39th St, Lawrenceville",la:40.4720,ln:-79.9560,
 w:"A family-run cidery in Lawrenceville pouring hard ciders and meads by the growler in a Civil-War-themed taproom — a low-key local institution.",
 k:"Taproom hours vary; growler fills. Approximate pin.",s:[["NP",""]]},
{t:3,a:"DT",cz:["DR"],n:"Dancing Gnome",ad:"1025 Main St, Sharpsburg",la:40.5000,ln:-79.9260,
 w:"A hop-forward Sharpsburg brewery beer nerds cross town for — hazy IPAs done with real precision in a relaxed taproom.",
 k:"Taproom hours vary. ~10 min north. Approximate pin.",s:[["NP",""]]},
{t:3,a:"DT",cz:["DR"],n:"Grist House Craft Brewery",ad:"10 E Sherman St, Millvale",la:40.4820,ln:-79.9760,
 w:"A well-loved Millvale brewery with a big outdoor deck and rotating small-batch beers — the kind of neighbourhood taproom Pittsburgh does well.",
 k:"Outdoor-friendly; food trucks. ~10 min north. Approximate pin.",s:[["NP",""]]},
{t:1,a:"DT",cz:["MKT"],n:"The Strip District",ad:"Penn Ave & Smallman St",la:40.4510,ln:-79.9770,
 w:"Pittsburgh's historic market district: a mile of ethnic grocers and food halls the city calls its essential food crawl, ranked among the top things to do in the whole city.",
 k:"Best Saturday mornings; much is closed Mondays. Permanent, publicly open. Approximate pin.",s:[["USN",""],["VP",""],["AO",""]]},
{t:1,a:"DT",cz:["MKT"],n:"Pennsylvania Macaroni Company (Penn Mac)",ad:"2010 Penn Ave, Strip District",la:40.4508,ln:-79.9805,
 w:"An iconic Italian grocery since 1902 — 400-plus imported cheeses cut to order at the counter, plus olive oils, cured meats and pantry goods stacked to the ceiling.",
 k:"The cheese counter is the whole experience. Approximate pin.",s:[["VP",""],["PGHMAG",""]]},
{t:1,a:"DT",cz:["MKT"],n:"Wholey's",ad:"1711 Penn Ave, Strip District",la:40.4498,ln:-79.9785,
 w:"A landmark fish market since 1912 — a suspended model train over the floor, a fresh seafood counter and a hot one-pound fried-cod sandwich.",
 k:"A Strip rite; go for the fish sandwich. Approximate pin.",s:[["VP",""],["DTB",""]]},
{t:2,a:"DT",cz:["MKT"],n:"Reyna Foods",ad:"2031 Penn Ave, Strip District",la:40.4509,ln:-79.9800,
 w:"The area's oldest Latin grocery (1987) — fresh corn tortillas and tamales off the line, with a taco window downstairs on weekends.",
 k:"Taco stand weekends. Approximate pin.",warn:1,s:[["CP",""],["NP",""]]},
{t:2,a:"OAK",cz:["MKT"],n:"Groceria Merante",ad:"3454 Bates St, Oakland",la:40.4300,ln:-79.9620,
 w:"A family Italian grocery and deli rooted in 1905 — house-made hot and mild sausage and imported prosciutto, its top seller — tucked below Oakland.",
 k:"Small; a real neighbourhood grocer. Approximate pin.",s:[["DTB",""]]},
{t:2,a:"OAK",cz:["MKT"],n:"Bloomfield Saturday Market",ad:"5050 Liberty Ave, Bloomfield",la:40.4620,ln:-79.9480,
 w:"An established (2014) farmers market of 40-plus vetted farm, fish and food vendors — Mediterra Bakehouse, Chantal's Cheese, Who Cooks For You Farm — in Little Italy.",
 k:"Sat 9–1 May–Oct; first & third Sat in winter. Publicly open. Approximate pin.",warn:1,s:[["NP",""],["VP",""]]},
{t:3,a:"OAK",cz:["MKT"],n:"Squirrel Hill Farmers Market",ad:"5737 Beacon St, Squirrel Hill",la:40.4360,ln:-79.9220,
 w:"A city-run Sunday market in the Beacon/Bartlett lot — farm produce, meats, cheese and baked goods, SNAP-accessible.",
 k:"Sun 9–1, May–Dec. Publicly open. Approximate pin.",warn:1,s:[["NP",""],["VP",""]]},
{t:3,a:"DT",cz:["MKT"],n:"Farmers@Firehouse",ad:"2216 Penn Ave, Strip District",la:40.4515,ln:-79.9765,
 w:"A long-running Saturday producers' market in the Strip with regional farms and prepared-food vendors around an old firehouse.",
 k:"Sat 9–1, May–Nov. Seasonal; publicly open. Approximate pin.",warn:1,s:[["VP",""],["NP",""]]},
{t:2,a:"DY",cz:["FARM"],n:"Soergel Orchards",ad:"2573 Brandt School Rd, Wexford, PA",la:40.6300,ln:-80.0700,
 w:"A family orchard north of the city since the 1850s: pick-your-own apples July–November, a farm market and bakery, a gift barn, and a hard-cider taproom. A proper agritourism day.",
 k:"Open much of the year; fall festival weekends. ~25 min north. Approximate pin.",s:[["VP",""],["KB",""]]},
{t:2,a:"DY",cz:["FARM"],n:"Trax Farms",ad:"528 Trax Rd, Finleyville, PA",la:40.2700,ln:-79.9900,
 w:"A South Hills fall-festival farm with pumpkin picking, a 3-acre corn maze, hayrides, a train ride, live music and food — a big family day out.",
 k:"Fall festival is the draw (Sept–Oct); market open longer. ~25 min south. Approximate pin.",warn:1,s:[["KB",""],["AXIOS",""]]},
{t:2,a:"DY",cz:["FARM"],n:"Triple B Farms",ad:"823 Berry Ln, Monongahela, PA",la:40.1800,ln:-79.9200,
 w:"A popular family farm about 15 miles south for apple and pumpkin picking, plus Pop's Farmyard with animals, hayrides and acres of fall fun.",
 k:"Seasonal (summer berries, fall apples/pumpkins). ~30 min south. Approximate pin.",warn:1,s:[["KB",""]]},
{t:2,a:"EV",cz:["FARM"],n:"Kerber's Dairy",ad:"1856 Guffey Rd, North Huntingdon, PA",la:40.3300,ln:-79.7300,
 w:"A working dairy on the family's last farm parcel making ~40 flavours of homemade ice cream daily, with goats and sheep to visit and an 18-hole mini-golf course.",
 k:"Petting animals summer/early fall. ~30 min east. Approximate pin.",warn:1,s:[["NP",""],["KB",""]]},
{t:2,a:"EV",cz:["FARM"],n:"Schramm Farms & Orchards \u2014 CLOSED",ad:"1002 Blank Rd, Jeannette, PA",la:40.3200,ln:-79.6100,
 w:"A family farm since 1864 with a year-round market, fresh cider and a fall pumpkin patch with hayrides.",
 k:"Confirm fall-festival hours by phone. ~40 min east. Approximate pin.",warn:1,s:[["CP",""],["KB",""]]},
{t:2,a:"SH",cz:["FARM"],n:"Bedner's Farm & Greenhouse",ad:"315 Coleman Rd, McDonald, PA",la:40.3600,ln:-80.2300,
 w:"A farm and greenhouse ~30 minutes southwest — pick-your-own pumpkins and vegetables, a corn maze, a petting zoo and hayrides, with a big fall festival.",
 k:"Retail Apr 1–Oct 31; fall festival is the draw. Approximate pin.",warn:1,s:[["VP",""],["KB",""]]},
{t:3,a:"DY",cz:["FARM"],n:"Janoski's Farm & Greenhouse",ad:"1714 Rt 30, Clinton, PA",la:40.3900,ln:-80.2900,
 w:"A family farm market and greenhouse — pick-your-own produce and pumpkins with hay rides, horse rides and a corn maze.",
 k:"Open year-round; fall is busiest. ~30 min west. Approximate pin.",warn:1,s:[["KB",""]]},
{t:3,a:"DY",cz:["FARM"],n:"Shenot Farm & Market",ad:"3754 Wexford Run Rd, Wexford, PA",la:40.6350,ln:-80.0900,
 w:"A 100-plus-acre fruit-and-vegetable farm since 1854 — pick-your-own blueberries, award-winning fresh-pressed cider, homemade fudge and pumpkin-patch hayrides.",
 k:"North Hills; seasonal crops. ~25 min north. Approximate pin.",warn:1,s:[["KB",""]]},
{t:3,a:"DY",cz:["FARM"],n:"Simmons Farm",ad:"170 Simmons Rd, McMurray, PA",la:40.2900,ln:-80.0900,
 w:"A South Hills u-pick farm with apples, pumpkins and flowers, hayrides, a petting zoo and an on-site market — easy fall fun with animals for the kids.",
 k:"Seasonal u-pick; check the crop schedule. ~30 min south. Approximate pin.",warn:1,s:[["KB",""]]}
];
'''

# ── Inject fact-checked coordinates from data/geocodes.json (SINGLE SOURCE OF TRUTH) ──
# Every place's lat/lng comes from the central registry, where each carries the source
# it was verified against. The build FAILS if any place lacks a sourced entry, so no pin
# is ever placed from memory. See docs/SOURCES.md and CLAUDE.md rule 4a.
import json as _json
_GEO = _json.load(open(os.path.join(ROOT, "data", "geocodes.json"), encoding="utf-8"))["cities"]["pittsburgh-pa"]
def _pf_names(s):
    names = []
    for marker in ("const P = [", "const F = ["):
        i = s.find(marker)
        if i < 0: continue
        j = s.find("\n];", i)
        names += re.findall(r'n:"((?:[^"\\]|\\.)*)"', s[i:(j if j > 0 else len(s))])
    return names
def _decode(raw):
    # registry keys are stored decoded (e.g. em dash), page names may carry JS \uXXXX escapes
    try: return _json.loads('"' + raw + '"')
    except Exception: return raw
_missing = []
for _name in _pf_names(DATA):
    _e = _GEO.get(_decode(_name)) or _GEO.get(_name)
    if not _e or _e.get("lat") is None or _e.get("lng") is None \
       or not _e.get("source") or _e.get("source") == "UNVERIFIED":
        _missing.append(_decode(_name)); continue
    _k = 'n:"' + _name + '"'; _i = DATA.find(_k); _j = min(len(DATA), _i + 800)
    _seg = DATA[_i:_j]
    _seg = re.sub(r'la:-?\d+\.\d+', "la:%.5f" % _e["lat"], _seg, count=1)
    _seg = re.sub(r'ln:-?\d+\.\d+', "ln:%.5f" % _e["lng"], _seg, count=1)
    DATA = DATA[:_i] + _seg + DATA[_j:]
assert not _missing, "GEOCODE GATE FAILED — %d place(s) lack a verified, sourced geocode in data/geocodes.json: %s" % (len(_missing), _missing[:12])
print("geocodes: injected verified coords for", len(_pf_names(DATA)), "places (0 missing)")

nP = DATA.count("{t:", DATA.index("const P = ["), DATA.index("const FS = {"))
nF = DATA.count("{t:", DATA.index("const F = ["), len(DATA))
TOTAL = nP + nF

start = h.index("const S = {")
anchor = h.index("P.forEach((p,i)=>{p.id='s'+i")
new = h[:start] + DATA.strip() + "\n\n" + h[anchor:]

def rep(a, b):
    global new
    assert a in new, "missing: " + a[:70]
    new = new.replace(a, b)

# map + area colours (two new regions: SH, EV)
rep("setView([41.4993,-81.6944],11)", "setView([40.4406,-79.9959],11)")
rep("const AC = {DT:'#74AE99',UC:'#C89B4A',WS:'#B45B3E',SUB:'#7E8FC4'};",
    "const AC = {DT:'#74AE99',OAK:'#C89B4A',SS:'#B45B3E',SH:'#8CA84E',EV:'#B57FC4',DY:'#7E8FC4'};")
rep("    --c-dt:#74AE99; --c-uc:#C89B4A; --c-ws:#B45B3E; --c-sub:#7E8FC4;",
    "    --c-dt:#74AE99; --c-uc:#C89B4A; --c-ws:#B45B3E; --c-sh:#8CA84E; --c-ev:#B57FC4; --c-sub:#7E8FC4;")
new = new.replace("cle_trip","pgh_trip").replace("cle_seen","pgh_seen").replace("cle_gkey","pgh_gkey")
new = new.replace("cleveland-my-list","pittsburgh-my-list").replace("cleveland-field-guide","pittsburgh-field-guide")
rep('''  <span><i style="background:var(--c-dt)"></i>Downtown</span>
  <span><i style="background:var(--c-uc)"></i>University Circle &amp; East</span>
  <span><i style="background:var(--c-ws)"></i>West Side &amp; Tremont</span>
  <span><i style="background:var(--c-sub)"></i>Suburbs &amp; day trips</span>''',
'''  <span><i style="background:var(--c-dt)"></i>Downtown &amp; North Side</span>
  <span><i style="background:var(--c-uc)"></i>Oakland &amp; East End</span>
  <span><i style="background:var(--c-ws)"></i>South Side &amp; Mt Washington</span>
  <span><i style="background:var(--c-sh)"></i>South Hills &amp; Southwest</span>
  <span><i style="background:var(--c-ev)"></i>East Suburbs &amp; Valleys</span>
  <span><i style="background:var(--c-sub)"></i>Day trips</span>''')
new = new.replace("all 183 places", "all %d places" % TOTAL)
new = new.replace(
'''const LABELS=[["Lake Erie",41.5600,-81.7400],["Downtown",41.4985,-81.6880],
 ["Ohio City",41.4845,-81.7080],["Tremont",41.4790,-81.6890],["Asiatown",41.5100,-81.6660],
 ["University Circle",41.5085,-81.6060],["Lakewood",41.4820,-81.7990],["Cuyahoga Valley",41.2600,-81.5600]];

backdrop=L.layerGroup().addTo(map);
L.polygon(SHORE.concat([[41.9000,-81.1000],[41.9000,-82.1000]]),
  {stroke:false,fillColor:'#16303A',fillOpacity:.55,interactive:false}).addTo(backdrop);
L.polyline(SHORE,{color:'#3E5D53',weight:1.6,opacity:.9,interactive:false}).addTo(backdrop);
L.polyline(RIVER,{color:'#2F5560',weight:2.2,opacity:.85,interactive:false}).addTo(backdrop);
ARTERIES.forEach(a=>L.polyline(a,{color:'#2E393E',weight:1.4,opacity:.8,interactive:false}).addTo(backdrop));
LABELS.forEach(''',
'''const LABELS=[["Downtown",40.4400,-80.0000],["North Side",40.4560,-80.0080],
 ["Strip District",40.4520,-79.9760],["Oakland",40.4420,-79.9530],["Lawrenceville",40.4660,-79.9600],
 ["Mount Washington",40.4300,-80.0110],["South Side",40.4280,-79.9750],["Carnegie",40.4090,-80.0850],
 ["Homestead",40.4060,-79.9120],["Washington PA",40.1720,-80.2460]];

// Real geography comes from the tiles; here we add only neighbourhood labels.
backdrop=L.layerGroup().addTo(map);
LABELS.forEach(''')
new = new.replace("so the map still shows Lake Erie, the\n   Cuyahoga and the main arteries even if every tile server is unreachable.",
                  "so subtle neighbourhood labels still show even if every tile server is unreachable.")
new = new.replace('placeholder="witchcraft, waterfall, chess, kielbasa…"',
                  'placeholder="incline, dinosaurs, relics, pierogi…"')
new = new.replace("? 'laksa, dim sum, pastrami, cannoli\\u2026' : 'witchcraft, waterfall, chess, kielbasa\\u2026'",
                  "? 'pierogi, soup dumplings, burnt almond torte, apples\\u2026' : 'incline, furnaces, warhol, trolley\\u2026'")
new = new.replace("'Every must-see (33)'", "'Every must-see ('+P.filter(p=>p.t===1).length+')'")
new = new.replace("Food, drink &amp; desserts", "Food, drink, markets &amp; farms")
new = new.replace(", Cleveland OH", ", Pittsburgh PA")
new = new.replace(">Cleveland \\u2014 my list<", ">Pittsburgh \\u2014 my list<")
new = new.replace(">Cleveland — my list<", ">Pittsburgh — my list<")
new = re.sub(r'<meta name="description"[^>]*>',
    '<meta name="description" content="Pittsburgh, PA field guide — %d sights and %d places to eat, drink, shop &amp; pick, each traceable to its source, on one interactive map with filters, a trip builder and exports.">' % (nP, nF),
    new)
rep("<title>Cleveland Field Guide — 130 Places, Sourced</title>",
    "<title>Pittsburgh Field Guide — The Steel City, Sourced</title>")
rep('<p class="eyebrow">Field guide · every place from all seven sources</p>',
    '<p class="eyebrow">Field guide · the Steel City, sourced</p>')
rep('<h1>Cleveland<span class="thin">the complete odd &amp; overlooked</span></h1>',
    '<h1>Pittsburgh<span class="thin">rivers, inclines &amp; the odd corners</span></h1>')
rep('<p class="standfirst">143 sights and 40 places to eat, each traceable to the source that named it. <strong>Switch modes below</strong> &mdash; food lives on its own map so it never clutters the sightseeing one. Tick the box on anything to build your own list, then export it to Google or Apple Maps.</p>',
    '<p class="standfirst">%d sights and %d places to eat, drink, shop &amp; pick across Greater Pittsburgh, each traceable to the source that named it. <strong>Switch modes below</strong> &mdash; the same map, filters, trip builder and exports as the Cleveland guide. Tick anything to build your own list, then export it to Google or Apple Maps.</p>' % (nP, nF))
rep('<p style="font-family:\'JetBrains Mono\',monospace;font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:var(--patina);margin:14px 0 0;">Last verified 2026-08-08 · <a href="index.html" style="color:var(--bone-dim);text-decoration:none;">← all cities</a></p>',
    '<p style="font-family:\'JetBrains Mono\',monospace;font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:var(--patina);margin:14px 0 0;">Last verified 2026-08-09 · <a href="../index.html" style="color:var(--bone-dim);text-decoration:none;">← all cities</a></p>')
rep('Compiled August 2026 · <strong>last verified 2026-08-08</strong>. Map tiles © OpenStreetMap contributors.<br>\n  <span style="opacity:.8">Refresh check (Aug 2026, via the pipeline): Sokolowski\'s University Inn confirmed still closed (kept, flagged); West Side Market open amid a $70M renovation, produce arcade reopened Jan 2026; newly opened since build — Rock &amp; Roll Hall of Fame expansion, Cleveland Metroparks Zoo Primate Forest, Irishtown Bend Park. Findings logged in data/sources.json.</span><br><br>',
    'Compiled August 2026 · <strong>last verified 2026-08-09</strong>. Map tiles © OpenStreetMap contributors.<br>\n  <span style="opacity:.8">Web-researched and fact-checked via the pipeline (data/sources.json, docs/SOURCES.md). Sourced across aggregator and guidebook rankings (Tripadvisor, U.S. News, PlanetWare, Lonely Planet, Britannica), the official institutions (Carnegie Museums, the Zoo, the National Aviary), university visitor guides (Pitt, CMU, Duquesne), regional heritage bodies (Rivers of Steel) and local news / CVBs recorded in data/local-media.json. Coordinates are approximate pending a places-API pass; confirm hours before a drive.</span><br><br>')
YT_APPENDIX = (
    "+ '<div class=\"srcrow\"><span class=\"k\">FOOD RULES</span><div class=\"t\">How the food, markets & farms list works'\n"
    "  + '<span>Pittsburgh classics anchor it \\u2014 the Primanti\\u2019s sandwich, pierogi, the burnt almond torte, soup dumplings. A cuisine tag needs a named dish; markets and farms must be genuinely visit-worthy and publicly open (see docs/SOURCES.md); anything tagged ADDED is general knowledge, verify it.</span></div></div>'\n"
    "  + '<div class=\"srcrow\"><span class=\"k\">HOW SOURCED</span><div class=\"t\">Web-searched and fact-checked'\n"
    "  + '<span>Found and cross-checked with web search across aggregator/guidebook rankings, the official institution sites, university visitor guides and the city\\u2019s local media (direct page fetches are blocked in the build environment). Ranked sources live in data/sources.json; the local-news map is data/local-media.json.</span></div></div>'\n"
    "  + '<div class=\"srcrow\"><span class=\"k\">COVERED BY</span><div class=\"t\">YouTube &amp; creators'\n"
    "  + '<span>Pittsburgh gets heavy travel-vlog coverage \\u2014 e.g. a \\u201cBritish Guy in Pittsburgh\\u201d tour of Mt Washington, Randyland and the museums, and 4K city tours. See the national creators catalogue in data/sources.json.</span></div></div>';"
)
new = re.sub(r"\+ '<div class=\"srcrow\"><span class=\"k\">FOOD RULES.*?</div></div>';",
             lambda m: YT_APPENDIX, new, flags=re.S)

open(OUT, "w", encoding="utf-8").write(new)
assert ", Cleveland OH" not in new and "P.forEach((p,i)=>{p.id='s'+i" in new
assert "Cleveland" not in new[new.index("const S = {"):new.index("const ALL")], "Cleveland leaked into data"
print("sights:", nP, "food:", nF, "total:", TOTAL)
print("remaining 'Cleveland':", new.count("Cleveland"))
print("OK wrote", OUT)
