#!/usr/bin/env python3
# Cross-city GEOCODE LEDGER. Scans data/geocodes.json (+ each dataset-built city's dataset) and
# reports, per city: verified pins by confidence, pins still UNVERIFIED (need the browser
# geocode-helper / a place-pin channel), low-confidence pins to re-verify, and — for dataset-built
# cities — ship-worthy places not yet in the registry at all. Writes docs/GEOCODE-BACKLOG.md so the
# outstanding geocode work for EVERY city/region is tracked in one place for any future agent.
#
#   python3 tools/geocode-status.py            # print + rewrite docs/GEOCODE-BACKLOG.md
#   python3 tools/geocode-status.py --print    # print only
import json, os, sys, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEO = json.load(open(os.path.join(ROOT, "data", "geocodes.json"), encoding="utf-8"))["cities"]
OPEN_ONLY = {"YELP", "TRIPADVISOR", "OPENTABLE", "GOOGLE", "GOOGLEMAPS"}
ELITE_SOLO = {"MICHELIN", "MICHELIN_BIB", "MICHELIN_STAR", "MICHELIN_GREEN", "JAMESBEARD"}

# dataset-built cities: key -> dataset path (source arrays live here; used to find not-yet-geocoded)
DATASETS = {
    "new-york-ny": "data/newyork.dataset.json",
    "silicon-valley-ca": "data/siliconvalley.dataset.json",
    "san-francisco-ca": "data/sanfrancisco.dataset.json",
}

def sourced_ok(rec):
    c = {t[0] for t in rec.get("s", []) if t[0] not in OPEN_ONLY}
    return len(c) >= 2 or bool(c & ELITE_SOLO)

def pinned(e):
    return bool(e and e.get("lat") is not None and e.get("source") and e.get("source") != "UNVERIFIED")

def audit_city(key):
    reg = GEO.get(key, {})
    conf = {"high": 0, "med": 0, "low": 0, "none": 0}
    unverified, low = [], []
    for n, e in reg.items():
        if not pinned(e):
            unverified.append(n); continue
        c = (e.get("confidence") or "none").lower()
        conf[c if c in conf else "none"] += 1
        if c == "low":
            low.append(n)
    verified = sum(conf.values())
    not_in_registry = []
    if key in DATASETS:
        p = os.path.join(ROOT, DATASETS[key])
        if os.path.exists(p):
            ds = json.load(open(p, encoding="utf-8"))
            ship = [r["n"] for r in ds.get("P", []) + ds.get("F", []) if sourced_ok(r)]
            not_in_registry = [n for n in ship if n not in reg]
    return {"registry": len(reg), "verified": verified, "conf": conf,
            "unverified": sorted(unverified), "low": sorted(low), "not_in_registry": sorted(not_in_registry)}

def main():
    lines = ["# Geocode backlog — all cities & regions",
             "",
             "_Auto-generated by `tools/geocode-status.py` — do not hand-edit; re-run to refresh._",
             "",
             "Every coordinate must be fact-checked against a real source (CLAUDE.md rule 4a/4b) and read",
             "from the **place pin** (`!3d!4d`), never a viewport. `UNVERIFIED` pins are held out by the",
             "build's geocode gate. Restaurant place-pins often will not surface via WebSearch here",
             "(WebFetch is blocked) — those are resolved with the browser **`tools/geocode-helper.html`**",
             "(reaches the map servers this sandbox cannot) or any Places-API channel.",
             ""]
    total_unv = total_low = total_missing = 0
    for key in sorted(GEO.keys()):
        a = audit_city(key)
        total_unv += len(a["unverified"]); total_low += len(a["low"]); total_missing += len(a["not_in_registry"])
        c = a["conf"]
        lines.append(f"## {key}")
        lines.append(f"- registry entries: **{a['registry']}** · verified pins: **{a['verified']}** "
                     f"(high {c['high']} · med {c['med']} · low {c['low']}"
                     + (f" · ungraded {c['none']}" if c['none'] else "") + ")")
        if a["not_in_registry"]:
            lines.append(f"- ⛔ ship-worthy but **NOT yet geocoded** ({len(a['not_in_registry'])}) — need a place-pin:")
            lines += [f"    - {n}" for n in a["not_in_registry"]]
        if a["unverified"]:
            lines.append(f"- ⚠️ **UNVERIFIED** in registry ({len(a['unverified'])}) — held by the gate, need the helper:")
            lines += [f"    - {n}" for n in a["unverified"]]
        if a["low"]:
            lines.append(f"- ↻ **low-confidence** ({len(a['low'])}) — re-verify to an exact place pin:")
            lines += [f"    - {n}" for n in a["low"]]
        if not (a["not_in_registry"] or a["unverified"] or a["low"]):
            lines.append("- ✅ no outstanding geocode work.")
        lines.append("")
    lines.insert(3, f"**Totals across all cities — not-yet-geocoded: {total_missing} · UNVERIFIED: {total_unv} · "
                    f"low-confidence to re-verify: {total_low}.**")
    report = "\n".join(lines) + "\n"
    print(report)
    if "--print" not in sys.argv:
        out = os.path.join(ROOT, "docs", "GEOCODE-BACKLOG.md")
        open(out, "w", encoding="utf-8").write(report)
        print(f"wrote {out}")

if __name__ == "__main__":
    main()
